from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SixRealmsAssets: 


	# Image Rule Assets
	# 宁息 
	I_NINGXI = RuleImage(file="a/ningxi.png", roi_front=(646,424,30,31), roi_back=(151,88,918,513), threshold=0.65, method="Template matching", path="./tasks/SixRealms/")
	# 混沌 
	I_HUNDUN = RuleImage(file="a/hundun.png", roi_front=(370,405,33,31), roi_back=(151,88,908,513), threshold=0.65, method="Template matching", path="./tasks/SixRealms/")
	# 鏖战 
	I_ZHAN = RuleImage(file="a/zhan.png", roi_front=(644,468,28,29), roi_back=(151,88,908,513), threshold=0.65, method="Template matching", path="./tasks/SixRealms/")
	# 神秘 
	I_SHENMI = RuleImage(file="a/shenmi.png", roi_front=(901,458,36,28), roi_back=(151,88,908,513), threshold=0.65, method="Template matching", path="./tasks/SixRealms/")
	# 星之屿 
	I_XING = RuleImage(file="a/xing.png", roi_front=(643,466,30,27), roi_back=(151,88,908,513), threshold=0.7, method="Template matching", path="./tasks/SixRealms/")


	# Click Rule Assets
	# description 
	C_MAIN_ANIMATE_KEEP = RuleClick(roi_front=(565,7,100,215), roi_back=(565,7,100,215), name="main_animate_keep")
	# description 
	C_STORE_ANIMATE_KEEP = RuleClick(roi_front=(825,87,317,466), roi_back=(825,87,317,466), name="store_animate_keep")


	# Image Rule Assets
	# 大boss挑战 
	I_BOSS_FIRE = RuleImage(file="gate1/gate1_boss_fire.png", roi_front=(1128,576,100,100), roi_back=(1091,557,156,147), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_TEAM_LOCK = RuleImage(file="gate1/gate1_boss_team_lock.png", roi_front=(1139,493,21,21), roi_back=(1130,487,38,43), threshold=0.95, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_TEAM_UNLOCK = RuleImage(file="gate1/gate1_boss_team_unlock.png", roi_front=(1138,497,22,21), roi_back=(1127,491,40,41), threshold=0.95, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_SKIP = RuleImage(file="gate1/gate1_boss_skip.png", roi_front=(1131,13,100,42), roi_back=(1113,5,136,62), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_USE_DOUBLE = RuleImage(file="gate1/gate1_boss_use_double.png", roi_front=(669,417,126,53), roi_back=(651,407,164,71), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 御神获得经验 
	I_BOSS_GET_EXP = RuleImage(file="gate1/gate1_boss_get_exp.png", roi_front=(561,109,171,45), roi_back=(492,86,281,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_SHARE = RuleImage(file="gate1/gate1_boss_share.png", roi_front=(1090,604,70,74), roi_back=(1074,587,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 结算的椒图（极） 
	I_BOSS_SHUTU = RuleImage(file="gate1/gate1_boss_shutu.png", roi_front=(108,141,173,122), roi_back=(108,141,173,122), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 结算的椒图（良） 
	I_BOSS_SHUTU_2 = RuleImage(file="gate1/gate1_boss_shutu_2.png", roi_front=(108,141,173,122), roi_back=(108,141,173,122), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BOSS_BATTLE_AGAIN = RuleImage(file="gate1/gate1_boss_battle_again.png", roi_front=(435,403,173,64), roi_back=(409,390,212,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 放弃前行 
	I_BOSS_BATTLE_GIVEUP = RuleImage(file="gate1/gate1_boss_battle_giveup.png", roi_front=(671,399,175,59), roi_back=(649,381,219,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 结算的(点击空白处继续) 
	I_BOSS_OVER = RuleImage(file="gate1/gate1_boss_over.png", roi_front=(539,669,173,37), roi_back=(539,669,173,37), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Click Rule Assets
	# 左边的 
	C_NPC_FIRE_LEFT = RuleClick(roi_front=(423,203,53,193), roi_back=(423,203,53,193), name="npc_fire_left")
	# description 
	C_NPC_FIRE_RIGHT = RuleClick(roi_front=(740,248,181,180), roi_back=(740,248,181,180), name="npc_fire_right")
	# 中间的精英 
	C_NPC_FIRE_CENTER = RuleClick(roi_front=(620,188,174,217), roi_back=(620,188,174,217), name="npc_fire_center")
	# 默认的 
	C_ISLAND_ENTER = RuleClick(roi_front=(0,0,100,100), roi_back=(0,0,100,100), name="island_enter")
	# 右数第一个 
	C_ISLAND_ENTER_1 = RuleClick(roi_front=(1012,349,136,221), roi_back=(1012,349,136,221), name="island_enter_1")
	# description 
	C_ISLAND_ENTER_2 = RuleClick(roi_front=(825,341,143,224), roi_back=(825,341,143,224), name="island_enter_2")
	# description 
	C_ISLAND_ENTER_3 = RuleClick(roi_front=(694,338,115,222), roi_back=(694,338,115,222), name="island_enter_3")
	# description 
	C_ISLAND_ENTER_4 = RuleClick(roi_front=(501,323,141,243), roi_back=(501,323,141,243), name="island_enter_4")
	# description 
	C_ISLAND_ENTER_5 = RuleClick(roi_front=(319,332,149,237), roi_back=(319,332,149,237), name="island_enter_5")
	# description 
	C_ISLAND_ENTER_6 = RuleClick(roi_front=(162,265,136,302), roi_back=(162,265,136,302), name="island_enter_6")


	# Image Rule Assets
	# description 
	I_MENTER = RuleImage(file="gate1/gate1_menter.png", roi_front=(346,167,30,100), roi_back=(346,167,30,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 酒吞 
	I_MSHUTEN = RuleImage(file="gate1/gate1_mshuten.png", roi_front=(46,609,70,65), roi_back=(46,609,70,65), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 椒图选中 
	I_MSHOUZU_SELECT = RuleImage(file="gate1/gate1_mshouzu_select.png", roi_front=(544,179,199,438), roi_back=(544,179,199,438), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 椒图 
	I_MSHOUZU = RuleImage(file="gate1/gate1_mshouzu.png", roi_front=(43,608,73,67), roi_back=(43,608,73,67), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 开启 
	I_MSTART = RuleImage(file="gate1/gate1_mstart.png", roi_front=(1136,575,100,100), roi_back=(1043,527,215,167), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_MSTART_CONFIRM = RuleImage(file="gate1/gate1_mstart_confirm.png", roi_front=(1136,575,100,100), roi_back=(1080,548,182,150), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_MSTART_UNCHECK = RuleImage(file="gate1/gate1_mstart_uncheck.png", roi_front=(543,340,38,40), roi_back=(543,340,38,40), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_MSTART_CHECK = RuleImage(file="gate1/gate1_mstart_check.png", roi_front=(542,340,39,41), roi_back=(542,340,39,41), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	#  
	I_MSKIP = RuleImage(file="gate1/gate1_mskip.png", roi_front=(1117,28,58,36), roi_back=(1117,28,58,36), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 左下角备战 
	I_PREPARE_BATTLE = RuleImage(file="gate1/gate1_prepare_battle.png", roi_front=(33,640,48,54), roi_back=(33,640,48,54), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 继续执行 
	I_MCONINUE = RuleImage(file="gate1/gate1_mconinue.png", roi_front=(1121,578,100,100), roi_back=(1121,578,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 选第一个柔风 
	I_MFIRST_SKILL = RuleImage(file="gate1/gate1_mfirst_skill.png", roi_front=(255,577,141,39), roi_back=(206,550,227,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 唤息 
	I_M_STORE = RuleImage(file="gate1/gate1_m_store.png", roi_front=(1124,594,61,57), roi_back=(1103,576,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 左上角退出 
	I_BACK_EXIT = RuleImage(file="gate1/gate1_back_exit.png", roi_front=(11,18,51,47), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 可以购买的幻息 
	I_M_STORE_ACTIVITY = RuleImage(file="gate1/gate1_m_store_activity.png", roi_front=(1121,596,72,57), roi_back=(1107,573,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_MSTART_CONFIRM2 = RuleImage(file="gate1/gate1_mstart_confirm2.png", roi_front=(1154,581,74,85), roi_back=(1079,535,196,177), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 动画完了就有这个东西 
	I_ISLAND_TAG_FLAG = RuleImage(file="gate1/gate1_island_tag_flag.png", roi_front=(543,601,100,100), roi_back=(543,601,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 暂时离开六道之门 
	I_EXIT_SIXREALMS = RuleImage(file="gate1/gate1_exit_sixrealms.png", roi_front=(507.5,308,100,100), roi_back=(507.5,308,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Ocr Rule Assets
	# Ocr-description 
	O_OCR_MAP = RuleOcr(roi=(144,227,989,376), area=(144,227,989,376), mode="Full", method="Default", keyword="", name="ocr_map")
	# Ocr-description 
	O_ISLAND_NAME = RuleOcr(roi=(88,17,148,49), area=(88,17,148,49), mode="Single", method="Default", keyword="", name="island_name")
	# 有多少钱 
	O_COIN_NUM = RuleOcr(roi=(1171,23,59,31), area=(1171,23,59,31), mode="Digit", method="Default", keyword="", name="coin_num")
	# 六道门票-椒图 
	O_SIXREALMS_NUMBER = RuleOcr(roi=(1151,23,59,33), area=(1151,23,59,33), mode="Digit", method="Default", keyword="", name="sixrealms_number")
	# Ocr-description 
	O_SKILL_REFRESH = RuleOcr(roi=(1172,684,100,31), area=(1172,684,100,31), mode="Single", method="Default", keyword="", name="skill_refresh")
	# 剩余回合数 
	O_REMAINING_NUMBER = RuleOcr(roi=(1074,233,82,22), area=(1074,233,82,22), mode="Single", method="Default", keyword="", name="remaining_number")


	# Image Rule Assets
	# 柔风 
	I_SKILL101 = RuleImage(file="gate1/gate1_skill101.png", roi_front=(440,181,100,69), roi_back=(139,167,722,100), threshold=0.6, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SKILL102 = RuleImage(file="gate1/gate1_skill102.png", roi_front=(456,186,76,63), roi_back=(136,151,709,128), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SKILL103 = RuleImage(file="gate1/gate1_skill103.png", roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SKILL104 = RuleImage(file="gate1/gate1_skill104.png", roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SKILL_REFRESH = RuleImage(file="gate1/gate1_skill_refresh.png", roi_front=(1196,625,44,39), roi_back=(1171,586,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SELECT_0 = RuleImage(file="gate1/gate1_select_0.png", roi_front=(152,572,132,44), roi_back=(140,542,163,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SELECT_1 = RuleImage(file="gate1/gate1_select_1.png", roi_front=(424,573,137,46), roi_back=(382,544,196,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_SELECT_2 = RuleImage(file="gate1/gate1_select_2.png", roi_front=(696,572,140,47), roi_back=(666,546,196,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 最右边的恢复生命 
	I_SELECT_3 = RuleImage(file="gate1/gate1_select_3.png", roi_front=(1016,581,145,43), roi_back=(1000,550,173,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 六道的金币 
	I_COIN = RuleImage(file="gate1/gate1_coin.png", roi_front=(612,345,66,53), roi_back=(405,229,561,270), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 六道的金币 
	I_COIN2 = RuleImage(file="gate1/gate1_coin.png", roi_front=(612,345,66,53), roi_back=(405,229,561,270), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 洞察之力 
	I_SKILL105 = RuleImage(file="gate1/gate1_skill105.png", roi_front=(178,187,80,69), roi_back=(112,149,779,151), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Image Rule Assets
	# 宁息刷新 
	I_STORE_REFRESH = RuleImage(file="l101/l101_store_refresh.png", roi_front=(545,596,46,47), roi_back=(519,568,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 购买柔风 
	I_STORE_SKILL_101 = RuleImage(file="l101/l101_store_skill_101.png", roi_front=(876,121,47,41), roi_back=(682,100,455,571), threshold=0.9, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_STORE_EXIT = RuleImage(file="l101/l101_store_exit.png", roi_front=(1179,586,59,56), roi_back=(1161,561,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 稳定标志 
	I_STORE_STABLE_FLAG = RuleImage(file="l101/l101_store_stable_flag.png", roi_front=(1028,251,28,27), roi_back=(1011,241,63,47), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Ocr Rule Assets
	# 刷新次数 
	O_STORE_REFRESH_TIME = RuleOcr(roi=(538,661,110,27), area=(538,661,110,27), mode="Single", method="Default", keyword="", name="store_refresh_time")


	# Image Rule Assets
	# 要花钱的界面购买 
	I_COIN_RIGHT_TOP = RuleImage(file="l102/l102_coin_right_top.png", roi_front=(1065,21,40,30), roi_back=(942,10,177,112), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_IMITATE = RuleImage(file="l102/l102_imitate.png", roi_front=(1157,598,100,100), roi_back=(1143,577,127,132), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 仿造的技能 
	I_IMITATE_1 = RuleImage(file="l102/l102_imitate_1.png", roi_front=(839,194,59,44), roi_back=(794,174,358,268), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_IMITATE_SUCCESS = RuleImage(file="l102/l102_imitate_success.png", roi_front=(535,143,209,54), roi_back=(429,122,414,100), threshold=0.7, method="Template matching", path="./tasks/SixRealms/")


	# Image Rule Assets
	# description 
	I_L103_EXIT = RuleImage(file="l103/l103_exit.png", roi_front=(1171,587,69,70), roi_back=(1078,538,195,180), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# lucky_box 
	I_LUCKY_BOX = RuleImage(file="l103/lucky_box.png", roi_front=(442,335,20,95), roi_back=(319,233,257,293), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Image Rule Assets
	# description 
	I_NPC_COMMON = RuleImage(file="l104/l104_npc_common.png", roi_front=(718,232,36,40), roi_back=(684,208,100,100), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# 点击挑战 
	I_NPC_FIRE = RuleImage(file="l104/l104_npc_fire.png", roi_front=(1129,585,100,100), roi_back=(1080,551,174,144), threshold=0.7, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BATTLE_TEAM_UNLOCK = RuleImage(file="l104/l104_battle_team_unlock.png", roi_front=(962,676,21,21), roi_back=(943,655,64,60), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# description 
	I_BATTLE_TEAM_LOCK = RuleImage(file="l104/l104_battle_team_lock.png", roi_front=(961,675,21,23), roi_back=(949,662,48,50), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")
	# fenghuang 
	I_FENGHUANG = RuleImage(file="l104/fenghuang.png", roi_front=(582,124,412,433), roi_back=(582,124,412,433), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


	# Image Rule Assets
	# 招福达摩 
	I_ZHAOFU = RuleImage(file="l105/zhaofu.png", roi_front=(421,270,22,51), roi_back=(382,205,97,214), threshold=0.8, method="Template matching", path="./tasks/SixRealms/")


