from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class PetsAssets: 


	# Image Rule Assets
	# 其乐融融 
	I_PET_HAPPY = RuleImage(file="pet/pet_pet_happy.png", roi_front=(853,614,67,70), roi_back=(853,614,67,70), threshold=0.8, method="Template matching", path="./tasks/Pets/")
	# 大餐 
	I_PET_FEAST = RuleImage(file="pet/pet_pet_feast.png", roi_front=(527,604,719,100), roi_back=(527,604,719,100), threshold=0.8, method="Template matching", path="./tasks/Pets/")
	# 玩耍 
	I_PET_PLAY = RuleImage(file="pet/pet_pet_play.png", roi_front=(788,500,75,75), roi_back=(788,500,75,75), threshold=0.8, method="Template matching", path="./tasks/Pets/")
	# 投喂 
	I_PET_FEED = RuleImage(file="pet/pet_pet_feed.png", roi_front=(884,488,127,111), roi_back=(884,488,127,111), threshold=0.8, method="Template matching", path="./tasks/Pets/")
	# 跳过 
	I_PET_SKIP = RuleImage(file="pet/pet_pet_skip.png", roi_front=(1089,119,72,41), roi_back=(999,42,242,147), threshold=0.65, method="Template matching", path="./tasks/Pets/")


	# Ocr Rule Assets
	# 投喂的体力 
	O_PET_FEED_AP = RuleOcr(roi=(819,537,57,33), area=(819,537,57,33), mode="Digit", method="Default", keyword="", name="pet_feed_ap")
	# 玩耍的体力 
	O_PET_PLAY_GOLD = RuleOcr(roi=(681,524,74,40), area=(681,524,74,40), mode="Digit", method="Default", keyword="", name="pet_play_gold")


