from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class WeeklyTriflesAssets:


	# Click Rule Assets
	# 进入已经挑战的第一个 
	C_WT_AB_CLICK = RuleClick(roi_front=(168,362,68,72), roi_back=(168,362,68,72), name="wt_ab_click")


	# Image Rule Assets
	# 今日挑战 
	I_WT_DAY_BATTLE = RuleImage(file="area_boss/area_boss_wt_day_battle.png", roi_front=(40,365,65,66), roi_back=(40,365,65,66), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 今天一个都没有打 
	I_WT_NO_DAY = RuleImage(file="area_boss/area_boss_wt_no_day.png", roi_front=(167,360,72,69), roi_back=(167,360,72,69), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 地鬼分享 
	I_WT_SHARE_AB = RuleImage(file="area_boss/area_boss_wt_share_ab.png", roi_front=(1167,74,91,349), roi_back=(1167,74,91,349), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 分享勾玉 
	I_WT_AB_JADE = RuleImage(file="area_boss/area_boss_wt_ab_jade.png", roi_front=(977,552,44,47), roi_back=(977,552,44,47), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 微信分享 
	I_WT_AB_WECHAT = RuleImage(file="area_boss/area_boss_wt_ab_wechat.png", roi_front=(845,643,50,41), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")


	# Click Rule Assets
	# 微信分享的点击 
	C_WT_WECHAT = RuleClick(roi_front=(470,111,337,44), roi_back=(470,111,337,44), name="wt_wechat")


	# Image Rule Assets
	# collect_wt_share 
	I_COLLECT_WT_SHARE = RuleImage(file="collect/collect_wt_share.png", roi_front=(23,197,455,238), roi_back=(23,197,455,238), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 点击“式神” 
	I_WT_SHIKIAGMI = RuleImage(file="collect/collect_wt_shikiagmi.png", roi_front=(280,620,920,100), roi_back=(280,620,920,100), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 点击式神绘卷 
	I_WT_SCROLL = RuleImage(file="collect/collect_wt_scroll.png", roi_front=(1128,615,77,67), roi_back=(1128,615,77,67), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 点击分享 
	I_WT_COLLECT = RuleImage(file="collect/collect_wt_collect.png", roi_front=(1170,606,78,83), roi_back=(1170,606,78,83), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 百鬼夜行图 
	I_WT_SCROLL_1 = RuleImage(file="collect/collect_wt_scroll_1.png", roi_front=(1180,27,28,121), roi_back=(1159,12,65,152), threshold=0.7, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 百妖风物鉴 
	I_WT_SCROLL_2 = RuleImage(file="collect/collect_wt_scroll_2.png", roi_front=(1182,24,24,122), roi_back=(1163,12,63,155), threshold=0.7, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 微信分享 
	I_WT_COLLECT_WECHAT = RuleImage(file="collect/collect_wt_collect_wechat.png", roi_front=(280,600,440,100), roi_back=(280,600,440,100), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 二维码 
	I_WT_QR_CODE = RuleImage(file="collect/collect_wt_qr_code.png", roi_front=(473,161,336,96), roi_back=(404,112,483,168), threshold=0.65, method="Template matching", path="./tasks/WeeklyTrifles/")


	# Image Rule Assets
	# 秘闻进入 
	I_WT_ENTER_SE = RuleImage(file="secret/secret_wt_enter_se.png", roi_front=(1145,598,100,100), roi_back=(1145,598,100,100), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 秘闻分享 
	I_WT_SE_SHARE = RuleImage(file="secret/secret_wt_se_share.png", roi_front=(897,559,85,64), roi_back=(897,559,85,64), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 微信 
	I_WT_SE_WECHAT = RuleImage(file="secret/secret_wt_se_wechat.png", roi_front=(786,627,45,37), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 勾玉 
	I_WT_SE_JADE = RuleImage(file="secret/secret_wt_se_jade.png", roi_front=(1123,532,35,39), roi_back=(1123,532,35,39), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")
	# 排行 
	I_WT_SE_RANK = RuleImage(file="secret/secret_wt_se_rank.png", roi_front=(1017,572,45,44), roi_back=(989,556,103,81), threshold=0.8, method="Template matching", path="./tasks/WeeklyTrifles/")


