from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SougenbiAssets: 


	# Click Rule Assets
	# description 
	C_C_GREED = RuleClick(roi_front=(172,144,299,100), roi_back=(172,144,299,100), name="c_greed")
	# description 
	C_C_ANGER = RuleClick(roi_front=(165,289,307,100), roi_back=(165,289,307,100), name="c_anger")
	# description 
	C_C_FOOLERY = RuleClick(roi_front=(166,435,303,100), roi_back=(166,435,303,100), name="c_foolery")


	# Image Rule Assets
	# 进入业原火 
	I_S_SOUGENBI = RuleImage(file="s/s_s_sougenbi.png", roi_front=(418,58,229,219), roi_back=(418,58,229,219), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	# 贪 
	I_S_GREED = RuleImage(file="s/s_s_greed.png", roi_front=(167,143,307,100), roi_back=(167,143,307,100), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	#  
	I_S_ANGER = RuleImage(file="s/s_s_anger.png", roi_front=(164,291,307,100), roi_back=(164,291,307,100), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	# 痴 
	I_S_FOOLERY = RuleImage(file="s/s_s_foolery.png", roi_front=(164,436,307,100), roi_back=(164,436,307,100), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	# description 
	I_S_TEAM_LOCK = RuleImage(file="s/s_s_team_lock.png", roi_front=(559,562,31,36), roi_back=(559,562,31,36), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	# description 
	I_S_TEAM_UNLOCK = RuleImage(file="s/s_s_team_unlock.png", roi_front=(555,561,33,33), roi_back=(555,561,33,33), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")
	# 进入业原火界面 
	I_S_CHECK_SOUGENBI = RuleImage(file="s/s_s_check_sougenbi.png", roi_front=(938,96,162,74), roi_back=(938,96,162,74), threshold=0.8, method="Template matching", path="./tasks/Sougenbi/")


	# List Rule Assets
	# 这个是御魂界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/Sougenbi/s", direction="vertical", mode="ocr", roi_back=(125,88,100,602), size=(40, 93), 
					 array=["贪之阵", "嗔之阵", "痴之阵"])


	# Ocr Rule Assets
	# Ocr-description 
	O_S_GREED = RuleOcr(roi=(591,15,50,30), area=(591,15,50,30), mode="Single", method="Default", keyword="", name="s_greed")
	# Ocr-description 
	O_S_ANGER = RuleOcr(roi=(770,15,50,30), area=(770,15,50,30), mode="Digit", method="Default", keyword="", name="s_anger")
	# Ocr-description 
	O_S_FOOLERY = RuleOcr(roi=(953,15,50,30), area=(953,15,50,30), mode="Digit", method="Default", keyword="", name="s_foolery")


