from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class SummonAssets: 


	# Image Rule Assets
	# summon_free 
	I_SUMMON_FREE = RuleImage(file="free/summon_free.png", roi_front=(34,216,32,35), roi_back=(14,82,73,369), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# summon_free_page 
	I_SUMMON_FREE_PAGE = RuleImage(file="free/summon_free_page.png", roi_front=(154,23,153,28), roi_back=(91,5,269,61), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# free_blue_ticket 
	I_FREE_BLUE_TICKET = RuleImage(file="free/free_blue_ticket.png", roi_front=(625,567,56,44), roi_back=(625,567,56,44), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# 点击继续 
	I_CLICK_TO_CONTINUE = RuleImage(file="free/click_to_continue.png", roi_front=(584,672,113,30), roi_back=(529,653,224,61), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")


	# Ocr Rule Assets
	# Ocr-description 
	O_FREE_TICKET = RuleOcr(roi=(619,622,70,26), area=(619,622,70,26), mode="Single", method="Default", keyword="", name="free_ticket")


	# Image Rule Assets
	# 点击蓝票 
	I_BLUE_TICKET = RuleImage(file="sm/sm_blue_ticket.png", roi_front=(595,586,65,76), roi_back=(523,563,211,111), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# 点击厕所票 
	I_LOW_TICKET = RuleImage(file="sm/sm_low_ticket.png", roi_front=(436,605,63,65), roi_back=(378,577,157,99), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# 单抽 
	I_ONE_TICKET = RuleImage(file="sm/sm_one_ticket.png", roi_front=(396,599,76,76), roi_back=(396,599,76,76), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# description 
	I_SM_CONFIRM = RuleImage(file="sm/sm_sm_confirm.png", roi_front=(419,617,174,61), roi_back=(419,617,174,61), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")
	# 抽到的时候出现的 
	I_SM_CONFIRM_2 = RuleImage(file="sm/sm_sm_confirm_2.png", roi_front=(377,630,206,62), roi_back=(377,630,206,62), threshold=0.8, method="Template matching", path="./tasks/Component/Summon/")


	# Ocr Rule Assets
	# Ocr-description 
	O_ONE_TICKET = RuleOcr(roi=(574,681,100,32), area=(574,681,100,32), mode="Single", method="Default", keyword="", name="one_ticket")


	# Swipe Rule Assets
	# description 
	S_RANDOM_SWIPE_1 = RuleSwipe(roi_front=(459,136,369,100), roi_back=(456,448,400,100), mode="default", name="random_swipe_1")
	# description 
	S_RANDOM_SWIPE_2 = RuleSwipe(roi_front=(433,451,447,100), roi_back=(411,122,479,100), mode="default", name="random_swipe_2")
	# description 
	S_RANDOM_SWIPE_3 = RuleSwipe(roi_front=(401,123,100,440), roi_back=(762,122,100,434), mode="default", name="random_swipe_3")
	# description 
	S_RANDOM_SWIPE_4 = RuleSwipe(roi_front=(777,128,100,412), roi_back=(431,120,100,444), mode="default", name="random_swipe_4")


