from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GameUiAssets: 


	# Image Rule Assets
	# description 
	I_PAPER_DOLL_CLOSE = RuleImage(file="additional/additional_paper_doll_close.png", roi_front=(1253,102,25,62), roi_back=(1238,58,40,153), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_ACT_LIST_EXPAND = RuleImage(file="additional/additional_act_list_expand.png", roi_front=(1191,508,30,25), roi_back=(1160,456,92,103), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Ocr Rule Assets
	# 点击空白处关闭此界面 
	O_CLICK_CLOSE_1 = RuleOcr(roi=(521,659,232,32), area=(521,659,232,32), mode="Single", method="Default", keyword="点击空白处关闭此界面", name="click_close_1")
	# 点击空白处关闭弹窗 
	O_CLICK_CLOSE_2 = RuleOcr(roi=(508,584,214,40), area=(508,584,214,40), mode="Single", method="Default", keyword="点击空白处关闭弹窗", name="click_close_2")


	# Image Rule Assets
	# description 
	I_AD_DISAPPEAR = RuleImage(file="additional/additional_ad_disappear.png", roi_front=(412,405,37,40), roi_back=(412,405,37,40), threshold=0.75, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_RECORDS_CLOSE = RuleImage(file="additional/additional_records_close.png", roi_front=(914,143,30,30), roi_back=(914,143,30,30), threshold=0.7, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# 左上角黄色返回 
	I_BACK_YELLOW = RuleImage(file="common/back_yellow.png", roi_front=(24,16,48,55), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 左上角蓝色返回 
	I_BACK_BLUE = RuleImage(file="common/back_blue.png", roi_front=(32,37,54,52), roi_back=(3,2,130,114), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 红色❌ 
	I_BACK_RED = RuleImage(file="common/back_red.png", roi_front=(1041,111,34,38), roi_back=(840,20,424,248), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 取消 
	I_BACK_CLOSE = RuleImage(file="common/back_close.png", roi_front=(452,428,79,35), roi_back=(399,383,217,106), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 刷新 
	I_REFRESH = RuleImage(file="common/refresh.png", roi_front=(1194,530,24,25), roi_back=(1167,123,66,445), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 活动总览 
	I_PAGE_ALL_ACTIVE = RuleImage(file="common/page_all_active.png", roi_front=(89,19,133,41), roi_back=(8,5,298,89), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 庭院到活动总览 
	I_PAGE_MAIN_GOTO_PAGE_ALL_ACTIVE = RuleImage(file="common/page_main_goto_page_all_active.png", roi_front=(1194,363,23,18), roi_back=(1174,134,71,439), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 右上跳过按钮（灰色） 
	I_SKIP_BUTTON = RuleImage(file="common/skip_button.png", roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 右上跳过按钮(蓝色) 
	I_SKIP_BUTTON_BLUE = RuleImage(file="common/skip_button_blue.png", roi_front=(1089,119,72,41), roi_back=(988,7,284,205), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 右上跳过按钮(十连召唤跳过) 
	I_SKIP_SUMMON = RuleImage(file="common/skip_summon.png", roi_front=(1115,70,52,22), roi_back=(1048,27,214,106), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 组队 
	I_FORM_TEAM = RuleImage(file="common/form_team.png", roi_front=(934,585,100,100), roi_back=(867,559,232,148), threshold=0.8, method="Template matching multi scale", path="./tasks/GameUi/")
	# 点击通用挑战 
	I_COMMON_FIRE = RuleImage(file="common/fire.png", roi_front=(989,547,274,160), roi_back=(989,547,274,160), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 再次挑战 
	I_AGAIN_BATTLE = RuleImage(file="common/again_battle.png", roi_front=(792,451,142,135), roi_back=(792,451,142,135), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 通用取消 
	I_CANCEL = RuleImage(file="common/cancel.png", roi_front=(465,386,143,76), roi_back=(377,367,243,198), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# 百鬼棋局大厅标志
	I_CHECK_CHESS = RuleImage(file="page/page_check_chess.png", roi_front=(1159,592,66,70), roi_back=(1159,592,66,70), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 鼬乐园->百鬼棋局
	I_ENTERTAINMENT_GOTO_CHESS = RuleImage(file="page/page_entertainment_goto_chess.png", roi_front=(304,175,41,127), roi_back=(304,175,41,127), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局局内页面标志 
	I_CHECK_CHESS_BATTLE = RuleImage(file="page/page_check_chess_battle.png", roi_front=(85,15,137,43), roi_back=(264,12,47,44), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局主动退出 
	I_CHESS_EXIT = RuleImage(file="page/page_chess_exit.png", roi_front=(12,14,48,38), roi_back=(12,14,48,38), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局确认退出 
	I_CHESS_EXIT_CONFIRM = RuleImage(file="page/page_chess_exit_confirm.png", roi_front=(716,409,88,45), roi_back=(716,409,88,45), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局退出确认弹窗 
	I_CHESS_EXIT_CANCEL = RuleImage(file="page/page_chess_exit_cancel.png", roi_front=(478,409,88,45), roi_back=(478,409,88,45), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局正常结算返回大厅 
	I_CHESS_EXIT_TO_LOBBY = RuleImage(file="page/page_chess_exit_to_lobby.png", roi_front=(384,591,172,47), roi_back=(340,570,270,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局主动退出后返回大厅 
	I_CHESS_EXIT_TO_LOBBY_2 = RuleImage(file="page/page_chess_exit_to_lobby_2.png", roi_front=(580,593,123,43), roi_back=(580,593,123,43), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局分享页 
	I_CHESS_SHARE = RuleImage(file="page/page_chess_share.png", roi_front=(1138,560,107,113), roi_back=(1138,560,107,113), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局排名页 
	I_CHECK_CHESS_RANK = RuleImage(file="page/page_check_chess_rank.png", roi_front=(14,75,79,38), roi_back=(14,75,79,38), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 百鬼棋局排名页返回大厅 
	I_CHESS_RANK_GOTO_LOBBY = RuleImage(file="page/page_chess_rank_goto_lobby.png", roi_front=(66,646,133,42), roi_back=(66,646,133,42), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# 庭院 
	I_CHECK_MAIN = RuleImage(file="page/page_check_main.png", roi_front=(801,109,38,37), roi_back=(49,98,1033,61), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 闲庭 
	I_PAGE_MAIN_RELAX = RuleImage(file="page/page_main_relax.png", roi_front=(49,607,52,45), roi_back=(49,607,52,45), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 庭院->探索 
	I_MAIN_GOTO_EXPLORATION = RuleImage(file="page/page_main_goto_exploration.png", roi_front=(493,116,45,75), roi_back=(243,100,933,211), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索界面 
	I_CHECK_EXPLORATION = RuleImage(file="page/page_check_exploration.png", roi_front=(1146,175,21,22), roi_back=(1069,76,192,120), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索玩法展开 
	I_EXPLORATION_EXPAND = RuleImage(file="page/exploration_expand.png", roi_front=(1241,118,20,20), roi_back=(1241,118,20,20), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->觉醒 
	I_EXPLORATION_GOTO_AWAKE_ZONE = RuleImage(file="page/page_exploration_goto_awake_zone.png", roi_front=(57,628,57,61), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->御魂 
	I_EXPLORATION_GOTO_SOUL_ZONE = RuleImage(file="page/page_exploration_goto_soul_zone.png", roi_front=(159,633,55,55), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->突破 
	I_EXPLORATION_GOTO_REALM_RAID = RuleImage(file="page/page_exploration_goto_realm_raid.png", roi_front=(248,636,67,48), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->御灵 
	I_EXPLORATION_GOTO_GORYOU_REALM = RuleImage(file="page/page_exploration_goto_goryou_realm.png", roi_front=(353,639,47,45), roi_back=(37,617,1169,87), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 探索->委派 
	I_EXPLORATION_GOTO_DELEGATION = RuleImage(file="page/page_exploration_goto_delegation.png", roi_front=(445,638,60,50), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->秘闻 
	I_EXPLORATION_GOTO_SECRET_ZONES = RuleImage(file="page/page_exploration_goto_secret_zones.png", roi_front=(546,628,61,55), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->地狱鬼王 
	I_EXPLORATION_GOTO_AREA_BOSS = RuleImage(file="page/page_exploration_goto_area_boss.png", roi_front=(640,638,51,45), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->平安奇谭 
	I_EXPLORATION_GOTO_HEIAN_KITAN = RuleImage(file="page/page_exploration_goto_heian_kitan.png", roi_front=(739,643,52,44), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->六道之门椒图 
	I_EXPLORATION_GOTO_SIX_GATES = RuleImage(file="page/page_exploration_goto_six_gates.png", roi_front=(838,640,60,49), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->六道之门觉 
	I_EXPLORATION_GOTO_SIX_GATES_JUE = RuleImage(file="page/page_exploration_goto_six_gates_jue.png", roi_front=(838,640,60,49), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索->契灵 
	I_EXPLORATION_GOTO_BONDLING_FAIRYLAND = RuleImage(file="page/page_exploration_goto_bondling_fairyland.png", roi_front=(937,639,56,49), roi_back=(37,617,1169,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 觉醒之塔界面 
	I_CHECK_AWAKE = RuleImage(file="page/page_check_awake.png", roi_front=(159,20,123,34), roi_back=(159,20,123,34), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 御魂副本界面 
	I_CHECK_SOUL_ZONES = RuleImage(file="page/page_check_soul_zones1.png", roi_front=(117,29,68,29), roi_back=(102,3,176,88), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 个突界面 
	I_CHECK_REALM_RAID = RuleImage(file="page/page_check_realm_raid.png", roi_front=(113,625,86,77), roi_back=(113,625,86,77), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 御灵之境界面 
	I_CHECK_GORYOU = RuleImage(file="page/page_check_goryou.png", roi_front=(158,21,121,29), roi_back=(158,21,121,29), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 委派界面 
	I_CHECK_DELEGATION = RuleImage(file="page/page_check_delegation.png", roi_front=(839,132,49,45), roi_back=(839,132,49,45), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 秘闻副本界面 
	I_CHECK_SECRET_ZONES = RuleImage(file="page/page_check_secret_zones.png", roi_front=(163,30,124,35), roi_back=(99,16,203,63), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 地域鬼王界面 
	I_CHECK_AREA_BOSS = RuleImage(file="page/page_check_area_boss.png", roi_front=(20,320,150,130), roi_back=(20,320,150,130), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 平安奇谭界面 
	I_CHECK_HEIAN_KITAN = RuleImage(file="page/page_check_heian_kitan.png", roi_front=(27,48,47,39), roi_back=(27,48,47,39), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 六道之门椒图界面 
	I_CHECK_SIX_GATES = RuleImage(file="page/page_check_six_gates.png", roi_front=(1174,621,55,44), roi_back=(1174,621,55,44), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 六道之门觉界面 
	I_CHECK_SIX_GATES_JUE = RuleImage(file="page/page_check_six_gates_jue.png", roi_front=(1174,621,55,44), roi_back=(1174,621,55,44), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 契灵之境界面 
	I_CHECK_BONDLING_FAIRYLAND = RuleImage(file="page/page_check_bondling_fairyland.png", roi_front=(614,660,56,49), roi_back=(614,660,56,49), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 个突->寮突 
	I_RYOUTOPPA_GOTO_REALMRAID = RuleImage(file="page/page_ryoutoppa_goto_realmraid.png", roi_front=(1201,234,62,105), roi_back=(1201,234,62,105), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# 宠物小屋 
	I_PET_HOUSE = RuleImage(file="page/pet_pet_house.png", roi_front=(1012,414,56,25), roi_back=(952,412,144,60), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 爪印 
	I_PET_CLAW = RuleImage(file="page/pet_pet_claw.png", roi_front=(1171,625,55,56), roi_back=(1171,625,55,56), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 庭院->町 
	I_MAIN_GOTO_TOWN = RuleImage(file="page/page_main_goto_town.png", roi_front=(706,249,61,57), roi_back=(200,120,951,298), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町 
	I_CHECK_TOWN = RuleImage(file="page/page_check_town.png", roi_front=(1026,106,68,82), roi_back=(765,98,402,96), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->庭院 
	I_TOWN_GOTO_MAIN = RuleImage(file="page/page_town_goto_main.png", roi_front=(1017,231,78,73), roi_back=(302,216,868,127), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->斗技 
	I_TOWN_GOTO_DUEL = RuleImage(file="page/page_town_goto_duel.png", roi_front=(756,142,48,68), roi_back=(357,126,657,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->逢魔 
	I_TOWN_GOTO_DEMON_ENCOUNTER = RuleImage(file="page/page_town_goto_demon_encounter.png", roi_front=(617,135,51,75), roi_back=(232,121,873,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 町->狩猎战 
	I_TOWN_GOTO_HUNT = RuleImage(file="page/page_town_goto_hunt.png", roi_front=(475,138,46,69), roi_back=(275,122,520,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 町->协同对弈 
	I_TOWN_GOTO_DRAFT_DUEL = RuleImage(file="page/page_town_goto_draft_duel.png", roi_front=(335,159,55,72), roi_back=(170,145,567,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->百鬼奕 
	I_TOWN_GOTO_HYAKKISEN = RuleImage(file="page/page_town_goto_hyakkisen.png", roi_front=(192,145,48,67), roi_back=(86,130,447,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 斗技界面 
	I_CHECK_DUEL = RuleImage(file="page/page_check_duel.png", roi_front=(110,10,64,38), roi_back=(76,9,162,60), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 逢魔界面 
	I_CHECK_DEMON_ENCOUNTER = RuleImage(file="page/page_check_demon_encounter.png", roi_front=(544,15,81,39), roi_back=(544,15,81,39), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 阴界之门界面 
	I_CHECK_NETHERWORLD = RuleImage(file="page/page_check_netherworld.png", roi_front=(575,30,46,25), roi_back=(553,1,81,68), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 麒麟界面 
	I_CHECK_KIRIN = RuleImage(file="page/page_check_kirin.png", roi_front=(91,20,96,36), roi_back=(42,8,248,72), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 百鬼奕界面 
	I_CHECK_HYAKKISEN = RuleImage(file="page/page_check_hyakkisen.png", roi_front=(1014,607,53,55), roi_back=(986,587,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 协同对弈界面 
	I_CHECK_DRAFT_DUEL = RuleImage(file="page/page_check_draft_duel.png", roi_front=(1051,612,56,58), roi_back=(1029,594,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->百鬼 
	I_TOWN_GOTO_HYAKKIYAKOU = RuleImage(file="page/page_town_goto_hyakkiyakou.png", roi_front=(880,165,53,69), roi_back=(827,149,148,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->百鬼2 
	I_TOWN_GOTO_HYAKKIYAKOU_2 = RuleImage(file="page/page_town_goto_hyakkiyakou_2.png", roi_front=(714,139,16,63), roi_back=(657,111,123,123), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 百鬼界面 
	I_CHECK_KYAKKIYAKOU = RuleImage(file="page/page_check_kyakkiyakou.png", roi_front=(305,567,56,64), roi_back=(280,545,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 町->鼬乐园
	I_TOWN_GOTO_ENTERTAINMENT = RuleImage(file="page/page_town_goto_entertainment.png", roi_front=(201,144,35,26), roi_back=(86,130,447,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 鼬乐园界面
	I_CHECK_ENTERTAINMENT = RuleImage(file="page/page_check_entertainment.png", roi_front=(151,18,102,40), roi_back=(151,18,102,40), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# 式神录 
	I_MAIN_GOTO_SHIKIGAMI_RECORDS = RuleImage(file="page/page_main_goto_shikigami_records.png", roi_front=(1098,611,56,64), roi_back=(1084,589,93,106), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_ONMYODO = RuleImage(file="page/page_main_goto_onmyodo.png", roi_front=(992,614,51,60), roi_back=(992,614,51,60), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_FRIENDS = RuleImage(file="page/page_main_goto_friends.png", roi_front=(879,623,55,55), roi_back=(33,591,1153,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 进入花合战 
	I_MAIN_GOTO_DAILY = RuleImage(file="page/page_main_goto_daily.png", roi_front=(779,612,51,67), roi_back=(33,591,1153,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_MALL = RuleImage(file="page/page_main_goto_mall.png", roi_front=(663,661,41,22), roi_back=(33,591,1153,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_GUILD = RuleImage(file="page/page_main_goto_guild.png", roi_front=(540,611,50,54), roi_back=(33,591,1153,100), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_TEAM = RuleImage(file="page/page_main_goto_team.png", roi_front=(437,625,38,48), roi_back=(366,606,192,83), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_COLLECTION = RuleImage(file="page/page_main_goto_collection.png", roi_front=(92,621,36,41), roi_back=(51,596,159,85), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_RECORDS = RuleImage(file="page/page_check_records.png", roi_front=(269,71,55,50), roi_back=(269,71,55,50), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_ONMYODO = RuleImage(file="page/page_check_onmyodo.png", roi_front=(1166,117,84,547), roi_back=(1166,117,84,547), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# page_check_friends 
	I_CHECK_FRIENDS = RuleImage(file="page/page_check_friends.png", roi_front=(594,50,146,31), roi_back=(519,10,290,120), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# page_check_daily 
	I_CHECK_DAILY = RuleImage(file="page/page_check_daily.png", roi_front=(102,23,97,36), roi_back=(20,7,236,74), threshold=0.7, method="Template matching", path="./tasks/GameUi/")
	# 商店页面 
	I_CHECK_MALL = RuleImage(file="page/page_check_mall.png", roi_front=(512,271,66,87), roi_back=(512,271,66,87), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 商店页面2 
	I_CHECK_MALL_2 = RuleImage(file="page/page_check_mall_2.png", roi_front=(170,31,123,22), roi_back=(170,31,123,22), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_GUILD = RuleImage(file="page/page_check_guild.png", roi_front=(1072,630,49,46), roi_back=(1072,630,49,46), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 结界界面 
	I_CHECK_REALM_SHIN = RuleImage(file="page/page_realm_shin.png", roi_front=(175,460,54,58), roi_back=(22,380,393,308), threshold=0.9, method="Template matching", path="./tasks/GameUi/")
	# 寮种树升级提示 
	I_CHECK_GUILD_CLOSE = RuleImage(file="page/page_check_guild_close.png", roi_front=(777,90,36,34), roi_back=(592,16,392,257), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_TEAM = RuleImage(file="page/page_check_team.png", roi_front=(92,24,77,38), roi_back=(17,5,232,102), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_COLLECTION = RuleImage(file="page/page_check_collection.png", roi_front=(380,620,100,100), roi_back=(394,610,854,105), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_BACK_MALL = RuleImage(file="page/page_back_mall.png", roi_front=(28,33,50,51), roi_back=(28,33,50,51), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_NEW = RuleImage(file="page/image_name.png", roi_front=(0,0,100,100), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 活动列表页返回庭院 
	I_BACK_ACT_LIST = RuleImage(file="page/page_back_act_list.png", roi_front=(1165,65,51,47), roi_back=(1124,23,131,133), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 下载拓展包弹窗 
	I_DLC_CLOSE = RuleImage(file="page/store_dlc_close.png", roi_front=(916,147,24,25), roi_back=(916,147,24,25), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 退出战斗按钮 
	I_BACK_BATTLE = RuleImage(file="page/page_back_battle.png", roi_front=(24,19,40,38), roi_back=(0,0,90,85), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Image Rule Assets
	# description 
	I_CHECK_LOGIN_FORM = RuleImage(file="page/page_check_login_form.png", roi_front=(178,572,53,60), roi_back=(1,500,400,150), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 登陆界面进入游戏 
	I_CHECK_LOGIN_ENTER_THE_GAME = RuleImage(file="page/page_check_login_enter_the_game.png", roi_front=(548,565,184,64), roi_back=(352,461,570,190), threshold=0.65, method="Template matching mask", path="./tasks/GameUi/")


	# Image Rule Assets
	# description 
	I_MAIN_GOTO_SUMMON = RuleImage(file="page/page_main_goto_summon.png", roi_front=(1073,174,57,65), roi_back=(571,153,586,124), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_SUMMON_GOTO_MAIN = RuleImage(file="page/page_summon_goto_main.png", roi_front=(27,5,49,51), roi_back=(0,0,100,100), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_CHECK_SUMMON = RuleImage(file="page/page_check_summon.png", roi_front=(581,594,68,66), roi_back=(316,528,594,174), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_MAIN_GOTO_TRAVEL = RuleImage(file="page/page_main_goto_travel.png", roi_front=(202,619,64,61), roi_back=(202,619,64,61), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 珍旅居 
	I_CHECK_TRAVEL = RuleImage(file="page/page_check_travel.png", roi_front=(1134,583,78,77), roi_back=(1134,583,78,77), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 活动列表页前往活动 
	I_ACT_LIST_GOTO_ACT = RuleImage(file="page/page_act_list_goto_act.png", roi_front=(1063,627,156,60), roi_back=(1007,552,272,166), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 活动列表页标志 
	I_CHECK_ACT_LIST = RuleImage(file="page/page_check_act_list.png", roi_front=(90,14,125,44), roi_back=(75,3,161,64), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 英杰试炼左上角标志 
	I_CHECK_HERO_TEST = RuleImage(file="page/page_check_hero_test.png", roi_front=(148,10,133,48), roi_back=(137,0,157,71), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 探索前往英杰试炼 
	I_EXPLORATION_GOTO_HERO_TEST = RuleImage(file="page/page_exploration_goto_hero_test.png", roi_front=(837,630,58,56), roi_back=(7,605,1272,113), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# List Rule Assets
	# 活动列表页图像列表 
	L_ACT_LIST_IMG = RuleList(folder="./tasks/GameUi/page", direction="vertical", mode="image", roi_back=(140,105,53,479), size=(46, 78), 
					 array=["climb_act"])


	# List Rule Assets
	# 活动列表页文字列表 
	L_ACT_LIST_OCR = RuleList(folder="./tasks/GameUi/page", direction="vertical", mode="ocr", roi_back=(219,91,47,513), size=(42, 78), 
					 array=["日之"])


	# Ocr Rule Assets
	# 战斗界面自动标识 
	O_BATTLE_AUTO = RuleOcr(roi=(37,642,51,36), area=(0,589,133,128), mode="Single", method="Default", keyword="自动", name="battle_auto")
	# 战斗页面手动标志 
	O_BATTLE_HAND = RuleOcr(roi=(35,644,52,34), area=(0,589,136,129), mode="Single", method="Default", keyword="手动", name="battle_hand")
	# 活动ocr范围 
	O_OCR_ACTIVE = RuleOcr(roi=(7,13,241,674), area=(7,13,241,674), mode="FULL", method="Default", keyword="版本活动", name="ocr_active")


	# Image Rule Assets
	# 式神录 
	I_HOME_SHIKIKAMI = RuleImage(file="res/res_home_shikikami.png", roi_front=(1092,611,73,41), roi_back=(1092,611,73,41), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 阴阳术 
	I_HOME_OMNYOUJI = RuleImage(file="res/res_home_omnyouji.png", roi_front=(989,613,59,58), roi_back=(989,613,59,58), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# description 
	I_HOME_FRIEND = RuleImage(file="res/res_home_friend.png", roi_front=(876,619,60,53), roi_back=(876,619,60,53), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 花合战 
	I_HOME_TSK = RuleImage(file="res/res_home_tsk.png", roi_front=(764,608,66,56), roi_back=(764,608,66,56), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 商店 
	I_HOME_MALL = RuleImage(file="res/res_home_mall.png", roi_front=(654,620,51,55), roi_back=(654,620,51,55), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 阴阳寮 
	I_HOME_GUILD = RuleImage(file="res/res_home_guild.png", roi_front=(540,607,53,50), roi_back=(540,607,53,50), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 组队 
	I_HOME_TEAM = RuleImage(file="res/res_home_team.png", roi_front=(430,616,49,61), roi_back=(430,616,49,61), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 同心队 
	I_HOME_CONCENTRIC_TEAM = RuleImage(file="res/res_home_concentric_team.png", roi_front=(310,618,67,60), roi_back=(310,618,67,60), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 珍旅居 
	I_HOME_HELP = RuleImage(file="res/res_home_help.png", roi_front=(201,617,56,57), roi_back=(201,617,56,57), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 图鉴 
	I_HOME_COLLECT = RuleImage(file="res/res_home_collect.png", roi_front=(92,607,48,74), roi_back=(92,607,48,74), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


	# Ocr Rule Assets
	# 庭院到探索 
	O_HOME_EXPLORE = RuleOcr(roi=(310,105,858,194), area=(0,0,100,100), mode="Full", method="Default", keyword="探索", name="home_explore")
	# Ocr-description 
	O_NEW = RuleOcr(roi=(0,0,100,100), area=(0,0,100,100), mode="Single", method="Default", keyword="", name="new")


	# Image Rule Assets
	# 登云问翠-战斗胜利 
	I_WIN_1 = RuleImage(file="win_false/gb_win_1.png", roi_front=(522,107,187,208), roi_back=(522,107,187,208), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 登云问翠-战斗失败 
	I_FALSE_1 = RuleImage(file="win_false/gb_false_1.png", roi_front=(701,138,181,200), roi_back=(701,138,181,200), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 茸茨跃动-战斗胜利 
	I_WIN_2 = RuleImage(file="win_false/gb_win_2.png", roi_front=(522,107,187,208), roi_back=(522,107,187,208), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 茸茨跃动-战斗失败 
	I_FALSE_2 = RuleImage(file="win_false/gb_false_2.png", roi_front=(701,138,181,200), roi_back=(701,138,181,200), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 招财纳福-战斗胜利 
	I_WIN_3 = RuleImage(file="win_false/gb_win_3.png", roi_front=(522,107,187,208), roi_back=(522,107,187,208), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 招财纳福-战斗失败 
	I_FALSE_3 = RuleImage(file="win_false/gb_false_3.png", roi_front=(516,137,215,198), roi_back=(516,137,215,198), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 藏金台阁-战斗胜利 
	I_WIN_4 = RuleImage(file="win_false/gb_false_4.png", roi_front=(391,100,100,100), roi_back=(296,33,414,224), threshold=0.8, method="Template matching", path="./tasks/GameUi/")
	# 藏金台阁-战斗失败 
	I_FALSE_4 = RuleImage(file="win_false/gb_false_4.png", roi_front=(384,106,100,100), roi_back=(346,96,184,120), threshold=0.8, method="Template matching", path="./tasks/GameUi/")


