from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CollectiveMissionsAssets: 


	# Click Rule Assets
	# description 
	C_CM_1 = RuleClick(roi_front=(231,468,141,55), roi_back=(231,468,141,55), name="cm_1")
	# description 
	C_CM_2 = RuleClick(roi_front=(567,468,143,55), roi_back=(567,468,143,55), name="cm_2")
	# description 
	C_CM_3 = RuleClick(roi_front=(903,470,136,58), roi_back=(903,470,136,58), name="cm_3")


	# Image Rule Assets
	# 神社 
	I_CM_SHRINE = RuleImage(file="cm/cm_cm_shrine.png", roi_front=(875,628,55,60), roi_back=(853,604,100,100), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 集体任务 
	I_CM_CM = RuleImage(file="cm/cm_cm_cm.png", roi_front=(157,169,210,161), roi_back=(137,131,246,235), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 提交 
	I_CM_PRESENT = RuleImage(file="cm/cm_cm_present.png", roi_front=(559,594,160,66), roi_back=(559,594,160,66), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 集体任务界面 
	I_CM_RECORDS = RuleImage(file="cm/cm_cm_records.png", roi_front=(550,39,134,53), roi_back=(550,39,134,53), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 将材料拉满的按钮，用来判断是否拉满 
	I_CM_MATTER = RuleImage(file="cm/cm_cm_matter.png", roi_front=(860,396,36,37), roi_back=(843,119,66,459), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# description 
	I_CM_ADD_1 = RuleImage(file="cm/cm_cm_add_1.png", roi_front=(904,142,48,48), roi_back=(904,142,48,48), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# description 
	I_CM_ADD_2 = RuleImage(file="cm/cm_cm_add_2.png", roi_front=(903,262,52,53), roi_back=(903,262,52,53), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# description 
	I_CM_ADD_3 = RuleImage(file="cm/cm_cm_add_3.png", roi_front=(904,389,48,45), roi_back=(904,389,48,45), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# description 
	I_CM_ADD_4 = RuleImage(file="cm/cm_cm_add_4.png", roi_front=(904,510,47,47), roi_back=(904,510,47,47), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 领取奖励 
	I_CM_REWARDS = RuleImage(file="cm/cm_cm_rewards.png", roi_front=(567,463,145,60), roi_back=(200,458,914,88), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 刷新 
	I_CM_FLUSH = RuleImage(file="cm/cm_cm_flush.png", roi_front=(416,489,37,31), roi_back=(416,489,37,31), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")


	# Ocr Rule Assets
	# Ocr-description 
	O_CM_1 = RuleOcr(roi=(217,133,115,43), area=(217,133,115,43), mode="Single", method="Default", keyword="", name="cm_1")
	# Ocr-description 
	O_CM_2 = RuleOcr(roi=(333,135,92,44), area=(333,135,92,44), mode="Single", method="Default", keyword="", name="cm_2")
	# Ocr-description 
	O_CM_3 = RuleOcr(roi=(554,135,113,40), area=(554,135,113,40), mode="Single", method="Default", keyword="", name="cm_3")
	# Ocr-description 
	O_CM_4 = RuleOcr(roi=(667,136,94,41), area=(667,136,94,41), mode="Single", method="Default", keyword="", name="cm_4")
	# Ocr-description 
	O_CM_5 = RuleOcr(roi=(889,133,112,44), area=(889,133,112,44), mode="Single", method="Default", keyword="", name="cm_5")
	# Ocr-description 
	O_CM_6 = RuleOcr(roi=(1002,133,91,42), area=(1002,133,91,42), mode="Single", method="Default", keyword="", name="cm_6")
	# 记录已完成的数量 
	O_CM_NUMBER = RuleOcr(roi=(1105,564,60,28), area=(1105,564,60,28), mode="DigitCounter", method="Default", keyword="", name="cm_number")
	# 材料的数量 
	O_CM_1_MATTER = RuleOcr(roi=(427,172,100,27), area=(427,172,100,27), mode="DigitCounter", method="Default", keyword="", name="cm_1_matter")
	# Ocr-description 
	O_CM_2_MATTER = RuleOcr(roi=(429,293,100,31), area=(429,293,100,31), mode="DigitCounter", method="Default", keyword="", name="cm_2_matter")
	# Ocr-description 
	O_CM_3_MATTER = RuleOcr(roi=(428,416,100,29), area=(428,416,100,29), mode="DigitCounter", method="Default", keyword="", name="cm_3_matter")
	# Ocr-description 
	O_CM_4_MATTER = RuleOcr(roi=(430,536,100,33), area=(430,536,100,33), mode="DigitCounter", method="Default", keyword="", name="cm_4_matter")


	# Swipe Rule Assets
	# description 
	S_CM_MATTER_1 = RuleSwipe(roi_front=(684,147,41,37), roi_back=(1060,142,46,41), mode="default", name="cm_matter_1")
	# description 
	S_CM_MATTER_2 = RuleSwipe(roi_front=(684,271,40,38), roi_back=(1066,261,45,49), mode="default", name="cm_matter_2")
	# description 
	S_CM_MATTER_3 = RuleSwipe(roi_front=(688,392,35,38), roi_back=(1117,388,50,45), mode="default", name="cm_matter_3")
	# description 
	S_CM_MATTER_4 = RuleSwipe(roi_front=(689,524,21,22), roi_back=(903,518,46,32), mode="default", name="cm_matter_4")


	# Image Rule Assets
	# 堆叠 
	I_FEED_HEAP = RuleImage(file="feed/feed_feed_heap.png", roi_front=(20,543,42,59), roi_back=(20,543,42,59), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 提交 
	I_FEED_SUBMIT = RuleImage(file="feed/feed_feed_submit.png", roi_front=(703,340,114,54), roi_back=(703,340,114,54), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")


	# Long Click Rule Assets
	# description 
	L_FEED_CLICK_1 = RuleLongClick(roi_front=(160,531,100,100), roi_back=(160,531,100,100), duration=1500, name="feed_click_1")
	# description 
	L_FEED_CLICK_2 = RuleLongClick(roi_front=(293,533,100,100), roi_back=(293,533,100,100), duration=1500, name="feed_click_2")
	# description 
	L_FEED_CLICK_3 = RuleLongClick(roi_front=(430,530,100,100), roi_back=(430,530,100,100), duration=1500, name="feed_click_3")
	# description 
	L_FEED_CLICK_4 = RuleLongClick(roi_front=(576,529,100,100), roi_back=(576,529,100,100), duration=1500, name="feed_click_4")


	# Image Rule Assets
	# 捐献勾玉加号 
	I_ADD_GUID_ICON = RuleImage(file="guid_icon/add_guid_icon.png", roi_front=(267,489,29,34), roi_back=(267,489,29,34), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 滑动捐献图标 
	I_HUA_LUN_BUTTON = RuleImage(file="guid_icon/hua_lun_button.png", roi_front=(503,368,21,42), roi_back=(421,345,431,88), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")
	# 捐勾玉 
	I_JUAN_GIDE = RuleImage(file="guid_icon/juan_gide.png", roi_front=(577,528,41,36), roi_back=(577,528,41,36), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")


	# Swipe Rule Assets
	# description 
	S_SWIPE_HUA_LUN_BUTTON = RuleSwipe(roi_front=(510,371,13,40), roi_back=(830,368,13,40), mode="default", name="swipe_hua_lun_button")


	# Image Rule Assets
	# 提交 
	I_SL_SUBMIT = RuleImage(file="soul/soul_sl_submit.png", roi_front=(835,588,145,61), roi_back=(835,588,145,61), threshold=0.8, method="Template matching", path="./tasks/CollectiveMissions/")


	# Long Click Rule Assets
	# 长按 
	L_SL_LONG = RuleLongClick(roi_front=(178,194,58,49), roi_back=(178,194,58,49), duration=1500, name="sl_long")


	# Ocr Rule Assets
	# +0 级 
	O_SL_LEVEL = RuleOcr(roi=(174,139,30,24), area=(174,139,30,24), mode="Single", method="Default", keyword="古", name="sl_level")
	# 将提交xx次任务 
	O_SL_NUMBER = RuleOcr(roi=(813,94,187,39), area=(813,94,187,39), mode="Single", method="Default", keyword="", name="sl_number")


