from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class RestartAssets: 


	# Image Rule Assets
	# 进入庭院事务记录按钮 
	I_COURTYARD_AFFAIRS_NOTES = RuleImage(file="courtyard_affairs/courtyard_affairs_notes.png", roi_front=(782,415,27,31), roi_back=(134,363,968,189), threshold=0.8, method="Template matching multi scale", path="./tasks/Restart/")
	# 进入庭院事务记录按钮1 
	I_COURTYARD_AFFAIRS_NOTES1 = RuleImage(file="courtyard_affairs/courtyard_affairs_notes1.png", roi_front=(510,478,20,22), roi_back=(134,363,968,189), threshold=0.8, method="Template matching multi scale", path="./tasks/Restart/")
	# 进入庭院事务按钮 
	I_COURTYARD_AFFAIRS_BUTTON = RuleImage(file="courtyard_affairs/courtyard_affairs_button.png", roi_front=(1189,299,35,33), roi_back=(1168,127,76,389), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 庭院事务主页面 
	I_COURTYARD_AFFAIRS_PAGE = RuleImage(file="courtyard_affairs/courtyard_affairs_page.png", roi_front=(277,41,160,51), roi_back=(277,41,160,51), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 一键完成 
	I_COMPLETE_WITH_ONE_CLICK = RuleImage(file="courtyard_affairs/complete_with_one_click.png", roi_front=(1128,600,70,67), roi_back=(1128,600,70,67), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 领取成功 
	I_SUCCESS_CLAIMED = RuleImage(file="courtyard_affairs/success_claimed.png", roi_front=(319,33,160,51), roi_back=(319,33,160,51), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 日常 
	I_DAILY = RuleImage(file="courtyard_affairs/daily.png", roi_front=(1140,135,63,52), roi_back=(1126,90,112,362), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 暂无可完成的任务 
	I_NO_TASKS_COMPLETE = RuleImage(file="courtyard_affairs/no_tasks_complete.png", roi_front=(537,225,210,32), roi_back=(537,225,210,32), threshold=0.8, method="Template matching", path="./tasks/Restart/")


	# Image Rule Assets
	# 点击勾玉 
	I_HARVEST_JADE = RuleImage(file="harvest/harvest_harvest_jade.png", roi_front=(732,489,34,33), roi_back=(177,451,973,141), threshold=0.8, method="Template matching mask", path="./tasks/Restart/")
	# 签到小图标 
	I_HARVEST_SIGN = RuleImage(file="harvest/harvest_harvest_sign.png", roi_front=(397,500,24,34), roi_back=(70,471,889,89), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# description 
	I_HARVEST_SIGN_2 = RuleImage(file="harvest/harvest_harvest_sign_2.png", roi_front=(592,135,100,252), roi_back=(592,135,100,252), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 999签到福袋 
	I_HARVEST_SIGN_999 = RuleImage(file="harvest/harvest_harvest_sign_999.png", roi_front=(345,494,23,29), roi_back=(51,459,888,103), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 邮件小图标 
	I_HARVEST_MAIL = RuleImage(file="harvest/harvest_harvest_mail.png", roi_front=(337,505,37,25), roi_back=(38,465,880,89), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 邮件右上角图标 
	I_HARVEST_MAIL_TOP_RIGHT = RuleImage(file="harvest/harvest_mail_top_right.png", roi_front=(1137,33,34,26), roi_back=(1128,5,67,52), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 一键领取 
	I_HARVEST_MAIL_ALL = RuleImage(file="harvest/harvest_harvest_mail_all.png", roi_front=(78,597,48,39), roi_back=(16,543,166,147), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 有些邮件需要点击一次 
	I_HARVEST_MAIL_OPEN = RuleImage(file="harvest/harvest_harvest_mail_open.png", roi_front=(163,367,45,48), roi_back=(139,86,100,487), threshold=0.9, method="Template matching", path="./tasks/Restart/")
	# 御魂加成 
	I_HARVEST_SOUL = RuleImage(file="harvest/harvest_harvest_soul.png", roi_front=(241,497,38,36), roi_back=(68,480,930,72), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 邮箱页面标头 
	I_HARVEST_MAIL_TITLE = RuleImage(file="harvest/harvest_harvest_mail_title.png", roi_front=(520,48,245,41), roi_back=(517,36,284,81), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 体力 
	I_HARVEST_AP = RuleImage(file="harvest/harvest_harvest_ap.png", roi_front=(721,486,31,38), roi_back=(206,462,970,134), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 打开聊天频道会自动关闭 
	I_HARVEST_CHAT_CLOSE = RuleImage(file="harvest/harvest_harvest_chat_close.png", roi_front=(639,309,35,100), roi_back=(620,280,70,200), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 签到 
	I_HARVEST_SIGN_3 = RuleImage(file="harvest/harvest_harvest_sign_3.png", roi_front=(291,495,33,36), roi_back=(100,473,1014,91), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# description 
	I_HARVEST_SIGN_4 = RuleImage(file="harvest/harvest_harvest_sign_4.png", roi_front=(587,151,100,228), roi_back=(547,123,185,281), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 点击随机御魂 
	I_HARVEST_SOUL_1 = RuleImage(file="harvest/harvest_harvest_soul_1.png", roi_front=(248,501,34,37), roi_back=(165,389,929,168), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 选择第一个御魂 
	I_HARVEST_SOUL_2 = RuleImage(file="harvest/harvest_harvest_soul_2.png", roi_front=(210,440,112,47), roi_back=(131,377,264,169), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# description 
	I_HARVEST_SOUL_3 = RuleImage(file="harvest/harvest_harvest_soul_3.png", roi_front=(313,489,188,33), roi_back=(302,472,216,60), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 寮包 
	I_HARVEST_GUILD_REWARD = RuleImage(file="harvest/harvest_harvest_guild_reward.png", roi_front=(244,498,41,42), roi_back=(200,403,817,157), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 宠物小屋关闭按钮 
	I_HARVEST_BACK_PET_HOUSE = RuleImage(file="harvest/harvest_back_pet_house.png", roi_front=(20,15,70,70), roi_back=(20,15,70,70), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 点击庭院阴阳师出现的姿度按钮 
	I_HARVEST_ZIDU = RuleImage(file="harvest/harvest_harvest_zidu.png", roi_front=(785,475,135,135), roi_back=(785,475,135,135), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# description 
	I_HARVEST_MAIL_COPY = RuleImage(file="harvest/harvest_harvest_mail_copy.png", roi_front=(257,509,29,21), roi_back=(192,472,790,100), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 邮件未读红点 
	I_MAIL_RED_DOTS = RuleImage(file="harvest/mail_red_dots.png", roi_front=(1153,14,36,26), roi_back=(1141,5,54,51), threshold=0.8, method="Template matching mask", path="./tasks/Restart/")
	# 寮消息通知 
	I_LIAO_MESSAGE = RuleImage(file="harvest/liao_message.png", roi_front=(189,138,35,34), roi_back=(35,50,358,248), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 确定收取邮件（位置比较靠下不能用通用确定） 
	I_HARVEST_MAIL_CONFIRM = RuleImage(file="harvest/harvest_harvest_mail_confirm.png", roi_front=(687,543,168,64), roi_back=(687,543,168,64), threshold=0.8, method="Template matching", path="./tasks/Restart/")


	# Click Rule Assets
	# 相同服务器多个角色选择界面,点击空白区域 登录 
	C_LOGIN_ENSURE_LOGIN_CHARACTER_IN_SAME_SVR = RuleClick(roi_front=(600,240,500,400), roi_back=(600,240,500,400), name="login_ensure_login_character_in_same_svr")


	# Image Rule Assets
	# 庭院卷轴打开状态 
	I_LOGIN_SCROOLL_OPEN = RuleImage(file="login/login_login_scrooll_open.png", roi_front=(1208,609,33,83), roi_back=(1208,609,33,83), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 庭院卷轴关闭状态 
	I_LOGIN_SCROOLL_CLOSE = RuleImage(file="login/login_login_scrooll_close.png", roi_front=(1181,634,28,39), roi_back=(1162,595,77,112), threshold=0.7, method="Template matching", path="./tasks/Restart/")
	# description 
	I_LOGIN_RED_CLOSE = RuleImage(file="login/login_login_red_close.png", roi_front=(800,0,480,290), roi_back=(800,0,480,290), threshold=0.7, method="Template matching", path="./tasks/Restart/")
	# description 
	I_LOGIN_YELLOW_CLOSE = RuleImage(file="login/login_login_yellow_close.png", roi_front=(29,17,46,44), roi_back=(0,0,94,86), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 用于判断是否出现登录选区的 
	I_LOGIN_8 = RuleImage(file="login/login_login_8.png", roi_front=(178,572,53,60), roi_back=(1,547,241,105), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 指定角色进入游戏,默认第一个 
	I_LOGIN_SPECIFIC_SERVE = RuleImage(file="login/login_login_specific_serve.png", roi_front=(0,0,120,120), roi_back=(0,0,120,120), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 下载插画 
	I_LOGIN_LOAD_DOWN = RuleImage(file="login/login_login_load_down.png", roi_front=(711,450,153,58), roi_back=(711,450,153,58), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 登录界面 弹出框 前往绑定 手机 
	I_LOGIN_LOGIN_GOTO_BIND_PHONE = RuleImage(file="login/login_login_goto_bind_phone.png", roi_front=(940,430,170,150), roi_back=(940,430,170,150), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 登录界面 弹出框 确定绑定手机 
	I_LOGIN_LOGIN_ENSURE_BIND_PHONE = RuleImage(file="login/login_login_ensure_bind_phone.png", roi_front=(670,460,160,100), roi_back=(670,460,160,100), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 登录界面 弹出框 阴阳师精灵 
	I_LOGIN_LOGIN_ONMYOJI_GENIE = RuleImage(file="login/login_login_onmyoji_genie.png", roi_front=(80,110,280,120), roi_back=(80,110,280,120), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 已有角色 
	I_CHARACTARS = RuleImage(file="login/login_charactars.png", roi_front=(246,535,100,31), roi_back=(219,523,173,57), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# description 
	I_CREATE_ACCOUNT = RuleImage(file="login/login_create_account.png", roi_front=(555,636,169,52), roi_back=(504,614,263,100), threshold=0.8, method="Template matching", path="./tasks/Restart/")
	# 4399登录会遇到活动-点击叉号 
	I_LOGIN_CLOSE = RuleImage(file="login/login_close.png", roi_front=(621,562,40,41), roi_back=(621,562,40,41), threshold=0.8, method="Template matching mask", path="./tasks/Restart/")


	# Ocr Rule Assets
	# 正在连接服务器 
	O_LOGIN_NETWORK = RuleOcr(roi=(534,649,189,39), area=(210,492,100,100), mode="Single", method="Default", keyword="正在连接服务器", name="login_network")
	# Ocr-description 
	O_LOGIN_ENTER_GAME = RuleOcr(roi=(550,567,176,56), area=(558,574,154,49), mode="Single", method="Default", keyword="进入游戏", name="login_enter_game")
	# 点击屏幕跳过 
	O_LOGIN_SKIP_1 = RuleOcr(roi=(1046,35,130,37), area=(1046,35,130,37), mode="Single", method="Default", keyword="点击屏幕跳过", name="login_skip_1")
	# 登录指定角色，默认第一个 
	O_LOGIN_SPECIFIC_SERVE = RuleOcr(roi=(110,120,350,600), area=(110,120,350,600), mode="Full", method="Default", keyword="", name="login_specific_serve")


