from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class NianTrueAssets: 


	# Click Rule Assets
	# description 
	C_CLIC_SAFE = RuleClick(roi_front=(242,25,100,65), roi_back=(242,25,100,65), name="clic_safe")


	# Image Rule Assets
	# 等待进入，也是关闭按钮 
	I_N_WAITING = RuleImage(file="nian/nian_n_waiting.png", roi_front=(735,28,54,51), roi_back=(735,28,54,51), threshold=0.7, method="Template matching", path="./tasks/NianTrue/")
	# 华北年兽 
	I_N_HUABEI = RuleImage(file="nian/nian_n_huabei.png", roi_front=(409,330,156,45), roi_back=(409,330,156,45), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 年兽战斗结束，通关奖励 
	I_BATTLE_OVER = RuleImage(file="nian/nian_battle_over.png", roi_front=(531,212,205,61), roi_back=(531,212,205,61), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 年兽来袭页面 
	I_N_PAGE = RuleImage(file="nian/nian_n_page.png", roi_front=(94,29,129,40), roi_back=(75,10,193,56), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 进入年兽按钮 
	I_GOTO_NIAN = RuleImage(file="nian/goto_nian.png", roi_front=(1190,219,39,32), roi_back=(1160,124,92,448), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 搜索年兽 
	I_NIAN_SEARCH = RuleImage(file="nian/nian_search.png", roi_front=(819,647,43,49), roi_back=(798,630,83,77), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 找到了年兽 
	I_IS_NIAN = RuleImage(file="nian/is_nian.png", roi_front=(605,261,71,60), roi_back=(605,261,71,60), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 组队挑战 
	I_FIRE_TEAM = RuleImage(file="nian/fire_team.png", roi_front=(1116,493,47,50), roi_back=(1116,493,47,50), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 创建队伍 
	I_CREATE_TEAM = RuleImage(file="nian/create_team.png", roi_front=(569,491,141,50), roi_back=(569,491,141,50), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")
	# 挑战按钮 
	I_FIRE_BUTTON = RuleImage(file="nian/fire_button.png", roi_front=(1193,618,50,49), roi_back=(1193,618,50,49), threshold=0.8, method="Template matching", path="./tasks/NianTrue/")


