from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityCommonAssets: 


	# Image Rule Assets
	# 活动商店图标 
	I_ACTIVE_STORE = RuleImage(file="active/active_store.png", roi_front=(959,639,37,31), roi_back=(915,597,115,107), threshold=0.8, method="Template matching", path="./tasks/ActivityCommon/")
	# 前往活动 
	I_GOTO_ACTIVE = RuleImage(file="active/goto_active.png", roi_front=(1076,638,135,37), roi_back=(1040,623,213,71), threshold=0.8, method="Template matching", path="./tasks/ActivityCommon/")


	# Ocr Rule Assets
	# 挑战名称（前端填入） 
	O_OCR_ACTIVE_BATTLE = RuleOcr(roi=(81,73,1142,526), area=(81,73,1142,526), mode="FULL", method="Default", keyword="", name="ocr_active_battle")


