from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EternitySeaAssets: 


	# Image Rule Assets
	# 选择永生之海 
	I_ETERNITY_SEA = RuleImage(file="res/res_eternity_sea.png", roi_front=(1139,93,127,416), roi_back=(1139,93,127,416), threshold=0.8, method="Template matching", path="./tasks/EternitySea/")


	# List Rule Assets
	# 永生之海层数列表 
	L_LAYER_LIST = RuleList(folder="./tasks/EternitySea/res", direction="vertical", mode="ocr", roi_back=(138,127,353,435), size=(56, 68), 
					 array=["壹", "贰", "叁", "肆"])


