from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DuelAssets: 


	# Click Rule Assets
	# 战斗数据 
	C_D_BATTLE_DATA = RuleClick(roi_front=(584,279,100,100), roi_back=(584,279,100,100), name="d_battle_data")
	# 从左开始第1个绿标 
	C_DUEL_GREEN_LEFT_1 = RuleClick(roi_front=(301,375,67,104), roi_back=(301,375,67,104), name="duel_green_left_1")
	# 从左开始第五个绿标 
	C_DUEL_GREEN_LEFT_5 = RuleClick(roi_front=(987,395,67,104), roi_back=(987,395,67,104), name="duel_green_left_5")
	# 补充点击位置 
	C_DUEL_GREEN_LEFT_FULL = RuleClick(roi_front=(0,0,0,0), roi_back=(0,0,0,0), name="duel_green_left_full")
	# 从左开始点击第1个是式神头像，获得式神名称 
	C_DUEL_CLICK_1 = RuleClick(roi_front=(105,23,52,47), roi_back=(105,23,52,47), name="duel_click_1")
	# 从左开始点击第2个是式神头像，获得式神名称 
	C_DUEL_CLICK_2 = RuleClick(roi_front=(180,23,52,47), roi_back=(180,23,52,47), name="duel_click_2")
	# 从左开始点击第3个是式神头像，获得式神名称 
	C_DUEL_CLICK_3 = RuleClick(roi_front=(250,23,52,47), roi_back=(250,23,52,47), name="duel_click_3")
	# 从左开始点击第4个是式神头像，获得式神名称 
	C_DUEL_CLICK_4 = RuleClick(roi_front=(320,23,52,47), roi_back=(320,23,52,47), name="duel_click_4")
	# 从左开始点击第5个是式神头像，获得式神名称 
	C_DUEL_CLICK_5 = RuleClick(roi_front=(390,23,52,47), roi_back=(390,23,52,47), name="duel_click_5")


	# Image Rule Assets
	# 点击阵容 
	I_D_TEAM = RuleImage(file="duel/duel_d_team.png", roi_front=(813,288,34,74), roi_back=(785,259,115,119), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 一键切换所有的御魂 
	I_D_TEAM_SWTICH = RuleImage(file="duel/duel_d_team_swtich.png", roi_front=(1082,85,38,41), roi_back=(1082,85,38,41), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 观战 
	I_D_VISIT = RuleImage(file="duel/duel_d_visit.png", roi_front=(1045,613,53,55), roi_back=(1045,613,53,55), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# description 
	I_D_BATTLE = RuleImage(file="duel/duel_d_battle.png", roi_front=(1153,573,100,100), roi_back=(1123,537,154,177), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 战斗带保护的 
	I_D_BATTLE_PROTECT = RuleImage(file="duel/duel_d_battle_protect.png", roi_front=(1153,578,100,100), roi_back=(1118,553,155,149), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 自动上阵 
	I_D_AUTO_ENTRY = RuleImage(file="duel/duel_d_auto_entry.png", roi_front=(30,123,44,47), roi_back=(30,123,44,47), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 取消自动上阵 
	I_D_AUTO_CANCEL = RuleImage(file="duel/duel_d_auto_cancel.png", roi_front=(30,123,44,47), roi_back=(30,123,44,47), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 手动，弃用 
	I_D_HAND = RuleImage(file="duel/duel_d_hand.png", roi_front=(34,635,55,55), roi_back=(34,635,55,55), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 主界面的感叹号 
	I_D_HELP = RuleImage(file="duel/duel_d_help.png", roi_front=(719,434,32,30), roi_back=(708,397,49,78), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 准备 
	I_D_PREPARE = RuleImage(file="duel/duel_d_prepare.png", roi_front=(1127,541,100,100), roi_back=(1127,541,100,100), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 准备完毕 
	I_D_PREPARE_DONE = RuleImage(file="duel/duel_d_prepare_done.png", roi_front=(495,82,75,55), roi_back=(495,82,75,55), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 战斗数据 
	I_D_BATTLE_DATA = RuleImage(file="duel/duel_d_battle_data.png", roi_front=(1068,610,38,60), roi_back=(1068,610,38,60), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 胜利 
	I_D_VICTORY = RuleImage(file="duel/duel_d_victory.png", roi_front=(433,76,100,100), roi_back=(433,76,100,100), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 失败 
	I_D_FAIL = RuleImage(file="duel/duel_d_fail.png", roi_front=(422,66,100,100), roi_back=(422,66,100,100), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 战 
	I_D_WORD_BATTLE = RuleImage(file="duel/duel_d_word_battle.png", roi_front=(612,41,54,54), roi_back=(612,41,54,54), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 名士的星星 
	I_D_CELEB_STAR = RuleImage(file="duel/duel_d_celeb_star.png", roi_front=(556,443,178,50), roi_back=(556,443,178,50), threshold=0.75, method="Template matching", path="./tasks/Duel/")
	# 名士专属 
	I_D_CELEB_HONOR = RuleImage(file="duel/duel_d_celeb_honor.png", roi_front=(665,531,25,30), roi_back=(652,517,52,53), threshold=0.75, method="Template matching", path="./tasks/Duel/")
	# 练 
	I_BATTLE_WITH_TRAIN = RuleImage(file="duel/duel_battle_with_train.png", roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 练2 
	I_BATTLE_WITH_TRAIN2 = RuleImage(file="duel/duel_battle_with_train2.png", roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 斗技模式（普通） 
	I_BATTLE_TYPE_COMMON = RuleImage(file="duel/duel_battle_type_common.png", roi_front=(439,278,90,88), roi_back=(439,278,90,88), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 活动的战斗按钮 
	I_D_BATTLE2 = RuleImage(file="duel/duel_d_battle2.png", roi_front=(1171,592,69,78), roi_back=(1119,566,154,143), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 禁用 
	I_BAN = RuleImage(file="duel/duel_ban.png", roi_front=(1112,537,100,100), roi_back=(1090,512,172,164), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 式神被办第五个上的式神跟原先不同，来判断是否被办 
	I_BAN_FLAG = RuleImage(file="duel/duel_ban_flag.png", roi_front=(100,16,61,59), roi_back=(100,16,61,59), threshold=0.7, method="Template matching", path="./tasks/Duel/")


	# Ocr Rule Assets
	# 荣誉 
	O_D_HONOR = RuleOcr(roi=(208,636,86,17), area=(208,636,86,17), mode="DigitCounter", method="Default", keyword="", name="d_honor")
	# 荣誉(小赛季) 
	O_D_HONOR1 = RuleOcr(roi=(149,665,105,24), area=(149,665,105,24), mode="DigitCounter", method="Default", keyword="", name="d_honor1")
	# 分数 
	O_D_SCORE = RuleOcr(roi=(606,487,45,22), area=(606,487,45,22), mode="Digit", method="Default", keyword="", name="d_score")
	# 名士星星数 
	O_D_CELEB_STAR = RuleOcr(roi=(689,453,77,37), area=(689,453,77,37), mode="Digit", method="Default", keyword="", name="d_celeb_star")
	# 手动 
	O_D_HAND = RuleOcr(roi=(31,639,63,45), area=(31,639,63,45), mode="Single", method="Default", keyword="手动", name="d_hand")
	# 自动 
	O_D_AUTO = RuleOcr(roi=(30,640,65,44), area=(30,640,65,44), mode="Single", method="Default", keyword="自动", name="d_auto")
	# 绿标获取 
	O_D_GREEN_MARKER = RuleOcr(roi=(111,202,1025,246), area=(111,202,1025,246), mode="Single", method="Default", keyword="456", name="d_green_marker")
	# 被办式神名称 
	O_D_BAN_NAME = RuleOcr(roi=(92,97,382,25), area=(92,97,382,25), mode="Single", method="Default", keyword="", name="d_ban_name")


	# Image Rule Assets
	# 区域找绿标1 
	I_GREEN_MARK = RuleImage(file="green_mark/green_mark.png", roi_front=(124,192,1012,197), roi_back=(124,192,1012,197), threshold=0.6, method="Template matching", path="./tasks/Duel/")
	# 区域找绿标2 
	I_GREEN_MARK_1 = RuleImage(file="green_mark/green_mark_1.png", roi_front=(124,192,1012,197), roi_back=(124,192,1012,197), threshold=0.6, method="Template matching", path="./tasks/Duel/")
	# 通过蒙版区域找绿标 
	I_GREEN_MARK_AUTO = RuleImage(file="green_mark/green_mark_auto.png", roi_front=(124,192,1012,197), roi_back=(124,192,1012,197), threshold=0.8, method="Template matching mask", path="./tasks/Duel/")
	# 区域找式神标记左1 
	I_GREEN_MARK_IMG1 = RuleImage(file="green_mark/green_mark_img.png", roi_front=(145,258,212,176), roi_back=(145,258,212,176), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 区域找式神标记左2 
	I_GREEN_MARK_IMG2 = RuleImage(file="green_mark/green_mark_img.png", roi_front=(397,262,163,176), roi_back=(397,262,163,176), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 区域找式神标记左3 
	I_GREEN_MARK_IMG3 = RuleImage(file="green_mark/green_mark_img.png", roi_front=(586,248,163,176), roi_back=(586,248,163,176), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 区域找式神标记左4 
	I_GREEN_MARK_IMG4 = RuleImage(file="green_mark/green_mark_img.png", roi_front=(749,271,163,176), roi_back=(749,271,163,176), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 区域找式神标记左5 
	I_GREEN_MARK_IMG5 = RuleImage(file="green_mark/green_mark_img.png", roi_front=(943,318,192,176), roi_back=(943,318,192,176), threshold=0.8, method="Template matching", path="./tasks/Duel/")
	# 都找不到用全位置匹配 
	I_GREEN_MARK_IMG_ALL = RuleImage(file="green_mark/green_mark_img.png", roi_front=(212,370,854,134), roi_back=(212,370,854,134), threshold=0.8, method="Template matching", path="./tasks/Duel/")


