from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GuildBanquetAssets: 


	# Image Rule Assets
	# description 
	I_FLAG = RuleImage(file="res/res_flag.png", roi_front=(1035,12,33,60), roi_back=(1035,12,33,60), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# description 
	I_SECRET_9_LAYER = RuleImage(file="res/secret_9_layer.png", roi_front=(188,354,39,25), roi_back=(91,253,484,410), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# 百战九层 
	I_SECRET_9_LAYER_BZ = RuleImage(file="res/secret_9_layer_bz.png", roi_front=(210,377,50,27), roi_back=(91,253,484,410), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# description 
	I_SECRET_9_LAYER_FLAG = RuleImage(file="res/secret_9_layer_flag.png", roi_front=(694,159,60,45), roi_back=(694,159,60,45), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# description 
	I_SECRET_HC = RuleImage(file="res/secret_hc.png", roi_front=(309,281,53,30), roi_back=(123,132,695,497), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# description 
	I_SECRET_HC_FLAG = RuleImage(file="res/secret_hc_flag.png", roi_front=(1010,243,43,56), roi_back=(864,147,347,316), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")
	# 秘闻挑战 
	I_SE_FIRE = RuleImage(file="res/se_se_fire.png", roi_front=(1015,503,182,188), roi_back=(1015,502,254,201), threshold=0.7, method="Template matching", path="./tasks/GuildBanquet/")
	# 百战秘闻挑战 
	I_SE_FIRE_BZ = RuleImage(file="res/se_se_fire_bz.png", roi_front=(1108,551,100,100), roi_back=(1100,541,120,120), threshold=0.7, method="Template matching", path="./tasks/GuildBanquet/")
	# 宴会进度10/10 
	I_GUILD_BANQUET_FINSH = RuleImage(file="res/guild_banquet_finsh.png", roi_front=(8,82,131,35), roi_back=(8,82,131,35), threshold=0.8, method="Template matching", path="./tasks/GuildBanquet/")


	# Swipe Rule Assets
	# 向下滑动 
	S_U_UP = RuleSwipe(roi_front=(247,520,43,20), roi_back=(247,180,43,20), mode="default", name="u_up")


