from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GlobalGameAssets: 


	# Image Rule Assets
	# 接受 
	I_G_ACCEPT = RuleImage(file="gg/gg_g_accept.png", roi_front=(830,407,56,46), roi_back=(798,369,117,110), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# 拒绝 
	I_G_REJECT = RuleImage(file="gg/gg_g_reject.png", roi_front=(832,508,53,51), roi_back=(808,480,108,101), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# 勾玉 
	I_G_JADE = RuleImage(file="gg/gg_g_jade.png", roi_front=(661,466,43,46), roi_back=(661,466,43,46), threshold=0.6, method="Template matching", path="./tasks/GlobalGame/")
	# 体力 
	I_G_SUSHI = RuleImage(file="gg/gg_g_sushi.png", roi_front=(661,466,43,46), roi_back=(661,466,43,46), threshold=0.6, method="Template matching", path="./tasks/GlobalGame/")
	# 猫粮 
	I_G_CAT_FOOD = RuleImage(file="gg/gg_g_cat_food.png", roi_front=(565,463,59,65), roi_back=(565,463,59,65), threshold=0.6, method="Template matching", path="./tasks/GlobalGame/")
	# 狗粮 
	I_G_DOG_FOOD = RuleImage(file="gg/gg_g_dog_food.png", roi_front=(565,464,60,63), roi_back=(565,464,60,63), threshold=0.6, method="Template matching", path="./tasks/GlobalGame/")
	# 忽略 
	I_G_IGNORE = RuleImage(file="gg/gg_g_ignore.png", roi_front=(773,116,21,21), roi_back=(759,102,48,48), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# description 
	I_CHAT_CLOSE_BUTTON = RuleImage(file="gg/gg_chat_close_button.png", roi_front=(632,343,49,103), roi_back=(632,343,49,103), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")


	# Click Rule Assets
	# description 
	C_UI_REWARD = RuleClick(roi_front=(919,160,208,368), roi_back=(72,107,244,503), name="ui_reward")


	# Image Rule Assets
	# 确定 
	I_UI_SURE = RuleImage(file="ui/ui_ui_sure.png", roi_front=(661,398,198,187), roi_back=(661,398,198,187), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# 确认 
	I_UI_CONFIRM = RuleImage(file="ui/ui_ui_confirm.png", roi_front=(655,300,260,180), roi_back=(655,300,260,180), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# '获得奖励' 四个大字 
	I_UI_REWARD = RuleImage(file="ui/ui_ui_reward.png", roi_front=(481,185,317,42), roi_back=(464,142,350,145), threshold=0.73, method="Template matching", path="./tasks/GlobalGame/")
	# 结算达摩（魂） 
	I_REWARD = RuleImage(file="ui/ui_ui_award.png", roi_front=(577,499,100,100), roi_back=(530,408,199,220), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# 未勾选 
	I_UI_UNCHECK = RuleImage(file="ui/ui_ui_uncheck.png", roi_front=(567,343,33,36), roi_back=(497,303,216,100), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")
	# 勾选 
	I_UI_CHECK = RuleImage(file="ui/ui_ui_check.png", roi_front=(564,341,40,38), roi_back=(512,329,164,78), threshold=0.8, method="Template matching", path="./tasks/GlobalGame/")


