from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class CostumeBattleAssets: 


	# Image Rule Assets
	# 指针 
	I_LOCAL_1 = RuleImage(file="battle1/battle1_local_1.png", roi_front=(119,493,23,25), roi_back=(119,493,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_1 = RuleImage(file="battle1/battle1_exit_1.png", roi_front=(21,20,27,31), roi_back=(21,20,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_1 = RuleImage(file="battle1/battle1_friends_1.png", roi_front=(88,18,35,34), roi_back=(88,18,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 左上角退出 
	I_EXIT_10 = RuleImage(file="battle10/battle10_exit_10.png", roi_front=(16,15,38,36), roi_back=(16,15,38,36), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_10 = RuleImage(file="battle10/battle10_friends_10.png", roi_front=(90,14,35,37), roi_back=(90,14,35,37), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 指针 
	I_LOCAL_10 = RuleImage(file="battle10/battle10_local_10.png", roi_front=(29,566,23,26), roi_back=(29,566,23,26), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 左上角退出 
	I_EXIT_11 = RuleImage(file="battle11/battle11_exit_11.png", roi_front=(16,15,31,34), roi_back=(16,15,40,40), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_11 = RuleImage(file="battle11/battle11_friends_11.png", roi_front=(90,14,30,28), roi_back=(90,14,40,40), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 指针 
	I_LOCAL_11 = RuleImage(file="battle11/battle11_local_11.png", roi_front=(29,566,29,28), roi_back=(29,566,40,40), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# description 
	I_LOCAL_2 = RuleImage(file="battle2/battle2_local_2.png", roi_front=(30,569,21,22), roi_back=(30,569,21,22), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# description 
	I_EXIT_2 = RuleImage(file="battle2/battle2_exit_2.png", roi_front=(17,16,35,34), roi_back=(17,16,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# description 
	I_FRIENDS_2 = RuleImage(file="battle2/battle2_friends_2.png", roi_front=(88,15,34,39), roi_back=(88,15,34,39), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_3 = RuleImage(file="battle3/battle3_local_3.png", roi_front=(29,567,23,25), roi_back=(29,567,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_3 = RuleImage(file="battle3/battle3_exit_3.png", roi_front=(23,18,27,31), roi_back=(23,18,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_3 = RuleImage(file="battle3/battle3_friends_3.png", roi_front=(89,17,35,34), roi_back=(89,17,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_4 = RuleImage(file="battle4/battle4_local_4.png", roi_front=(29,567,23,25), roi_back=(29,567,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_4 = RuleImage(file="battle4/battle4_exit_4.png", roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_4 = RuleImage(file="battle4/battle4_friends_4.png", roi_front=(88,16,35,34), roi_back=(88,16,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_5 = RuleImage(file="battle5/battle5_local_5.png", roi_front=(30,567,23,25), roi_back=(30,567,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_5 = RuleImage(file="battle5/battle5_exit_5.png", roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_5 = RuleImage(file="battle5/battle5_friends_5.png", roi_front=(90,17,35,34), roi_back=(90,17,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_6 = RuleImage(file="battle6/battle6_local_6.png", roi_front=(30,566,23,25), roi_back=(30,566,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_6 = RuleImage(file="battle6/battle6_exit_6.png", roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_6 = RuleImage(file="battle6/battle6_friends_6.png", roi_front=(89,18,35,34), roi_back=(89,18,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_7 = RuleImage(file="battle7/battle7_local_7.png", roi_front=(30,566,23,25), roi_back=(30,566,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_7 = RuleImage(file="battle7/battle7_exit_7.png", roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_7 = RuleImage(file="battle7/battle7_friends_7.png", roi_front=(89,18,35,34), roi_back=(89,18,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 指针 
	I_LOCAL_8 = RuleImage(file="battle8/battle8_local_8.png", roi_front=(30,566,23,25), roi_back=(30,566,23,25), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角退出 
	I_EXIT_8 = RuleImage(file="battle8/battle8_exit_8.png", roi_front=(22,17,27,31), roi_back=(22,17,27,31), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_8 = RuleImage(file="battle8/battle8_friends_8.png", roi_front=(89,18,35,34), roi_back=(89,18,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 战斗胜利 
	I_WIN_8 = RuleImage(file="battle8/battle8_win_8.png", roi_front=(391,100,100,100), roi_back=(296,33,414,224), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 针对封魔的特殊 
	I_DE_WIN_8 = RuleImage(file="battle8/battle8_de_win_8.png", roi_front=(392,99,100,100), roi_back=(239,36,399,198), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 失败 
	I_FALSE_8 = RuleImage(file="battle8/battle8_false_8.png", roi_front=(384,106,100,100), roi_back=(346,96,184,120), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


	# Image Rule Assets
	# 左上角退出 
	I_EXIT_9 = RuleImage(file="battle9/battle9_exit_9.png", roi_front=(20,17,35,34), roi_back=(20,17,35,34), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 左上角好友 
	I_FRIENDS_9 = RuleImage(file="battle9/battle9_friends_9.png", roi_front=(93,15,31,36), roi_back=(93,15,31,36), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")
	# 指针 
	I_LOCAL_9 = RuleImage(file="battle9/battle9_local_9.png", roi_front=(114,489,37,37), roi_back=(114,489,37,37), threshold=0.8, method="Template matching", path="./tasks/Component/CostumeBattle/")


