from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class LBSAssets: 


	# Image Rule Assets
	# flush 
	I_FLUSH = RuleImage(file="res/flush.png", roi_front=(1189,243,31,30), roi_back=(1163,138,82,404), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 1 
	I_1 = RuleImage(file="res/1.png", roi_front=(1189,243,31,30), roi_back=(1163,138,82,404), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 2 
	I_2 = RuleImage(file="res/2.png", roi_front=(1130,570,64,58), roi_back=(1130,570,64,58), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 3 
	I_3 = RuleImage(file="res/3.png", roi_front=(963,492,39,34), roi_back=(963,492,39,34), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 4 
	I_4 = RuleImage(file="res/4.png", roi_front=(598,493,79,35), roi_back=(598,493,79,35), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 5 
	I_5 = RuleImage(file="res/5.png", roi_front=(1196,617,54,45), roi_back=(1196,617,54,45), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 6 
	I_6 = RuleImage(file="res/6.png", roi_front=(1149,562,63,45), roi_back=(1149,562,63,45), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 7 
	I_7 = RuleImage(file="res/7.png", roi_front=(463,98,61,63), roi_back=(463,98,61,63), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 8 
	I_8 = RuleImage(file="res/8.png", roi_front=(611,521,54,56), roi_back=(611,521,54,56), threshold=0.8, method="Template matching", path="./tasks/LBS/")
	# 9 
	I_9 = RuleImage(file="res/9.png", roi_front=(589,454,95,39), roi_back=(589,454,95,39), threshold=0.8, method="Template matching", path="./tasks/LBS/")


