from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OrochiAssets: 


	# Image Rule Assets
	# 八级大蛇进入 
	I_OROCHI = RuleImage(file="o/o_orochi.png", roi_front=(55,104,295,406), roi_back=(55,104,295,406), threshold=0.8, method="Template matching", path="./tasks/Orochi/")
	# 组队 
	I_FORM_TEAM = RuleImage(file="o/o_form_team.png", roi_front=(937,591,100,100), roi_back=(937,591,100,100), threshold=0.8, method="Template matching", path="./tasks/Orochi/")
	# description 
	I_OROCHI_LOCK = RuleImage(file="o/o_orochi_lock.png", roi_front=(628,650,64,46), roi_back=(628,650,64,46), threshold=0.8, method="Template matching", path="./tasks/Orochi/")
	# description 
	I_OROCHI_UNLOCK = RuleImage(file="o/o_orochi_unlock.png", roi_front=(628,650,64,46), roi_back=(628,650,64,46), threshold=0.8, method="Template matching", path="./tasks/Orochi/")
	# 式神录 
	I_SHI_RECORDS = RuleImage(file="o/o_shi_records.png", roi_front=(821,638,48,45), roi_back=(821,638,48,45), threshold=0.8, method="Template matching", path="./tasks/Orochi/")
	# 小小宠物，发现宝藏 
	I_PET_PRESENT = RuleImage(file="o/o_pet_present.png", roi_front=(873,184,62,147), roi_back=(873,184,62,147), threshold=0.8, method="Template matching", path="./tasks/Orochi/")


	# List Rule Assets
	# 这个是御魂界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/Orochi/res", direction="vertical", mode="ocr", roi_back=(125,88,80,602), size=(45, 88), 
					 array=["壹层", "贰层", "叁层", "肆层", "伍层", "陆层", "柒层", "捌层", "玖层", "拾层", "悲鸣", "神罚", "虚无"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_test_ocr")


