from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class NetherworldAssets: 


	# Image Rule Assets
	# 彼世逢魔页面 
	I_PAGE_NETHERWORLD = RuleImage(file="o/page_netherworld.png", roi_front=(158,21,117,32), roi_back=(158,21,117,32), threshold=0.8, method="Template matching", path="./tasks/Netherworld/")
	# 逢魔之时2 
	I_PAGE_DEMON_ENCOUNTER_2 = RuleImage(file="o/page_demon_encounter_2.png", roi_front=(158,21,117,32), roi_back=(158,21,117,32), threshold=0.8, method="Template matching", path="./tasks/Netherworld/")
	# 进入彼世逢魔页面 
	I_ENTER_NETHERWORLD = RuleImage(file="o/enter_netherworld.png", roi_front=(495,145,67,50), roi_back=(495,145,67,50), threshold=0.8, method="Template matching", path="./tasks/Netherworld/")
	# 组队 
	I_FORM_TEAM = RuleImage(file="o/form_team.png", roi_front=(963,608,72,35), roi_back=(963,608,72,35), threshold=0.8, method="Template matching", path="./tasks/Netherworld/")
	# 挑战 
	I_FIRE = RuleImage(file="o/fire.png", roi_front=(1150,603,63,41), roi_back=(1150,603,63,41), threshold=0.8, method="Template matching", path="./tasks/Netherworld/")


