from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DokanAssets: 


	# Click Rule Assets
	# 选择寮 
	C_DOKAN_READY_SEL = RuleClick(roi_front=(1113,179,100,100), roi_back=(1113,179,100,100), name="dokan_ready_sel")
	# 道馆随机点击安全区域 
	C_DOKAN_RANDOM_CLICK_AREA = RuleClick(roi_front=(142,294,107,555), roi_back=(142,294,107,555), name="dokan_random_click_area")
	# 道馆随机点击安全区域1：竂友突破信息 
	C_DOKAN_RANDOM_CLICK_AREA1 = RuleClick(roi_front=(42,594,10,100), roi_back=(42,594,10,100), name="dokan_random_click_area1")
	# 道馆随机点击安全区域2：切换查看队伍模式。初步测试下来这个地方最安全，除了庭院、町中、逢魔外其他各场景都可用。 
	C_DOKAN_RANDOM_CLICK_AREA2 = RuleClick(roi_front=(1122,360,10,40), roi_back=(1122,360,10,40), name="dokan_random_click_area2")
	# 道馆随机点击安全区域3 
	C_DOKAN_RANDOM_CLICK_AREA3 = RuleClick(roi_front=(333,44,107,20), roi_back=(333,44,107,20), name="dokan_random_click_area3")
	# 准备战斗 
	C_DOKAN_READY_FOR_BATTLE = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="dokan_ready_for_battle")
	# 道馆从左开始第五个绿标 
	C_DOKAN_GREEN_LEFT_5 = RuleClick(roi_front=(1006,482,38,96), roi_back=(1006,482,38,96), name="dokan_green_left_5")
	# 查找道馆时 点击此区域 隐藏道馆详情(显示防守人数,馆主等级等的卡片) 
	C_DOKAN_CANCEL_SELECT_DOKAN = RuleClick(roi_front=(1070,610,30,90), roi_back=(1070,610,30,90), name="dokan_cancel_select_dokan")
	# ruleanimate 用作检测选择道馆时,确定地图区域稳定无动作 
	C_DOKAN_CANCEL_SELECT_DOKAN_CHECK_ANIMATE = RuleClick(roi_front=(600,330,80,60), roi_back=(600,330,80,60), name="dokan_cancel_select_dokan_check_animate")
	# 查找道馆时 刷新道馆列表 
	C_DOKAN_REFRESH = RuleClick(roi_front=(1140,630,40,30), roi_back=(1140,630,40,30), name="dokan_refresh")
	# 道馆战斗时,左上角 退出按钮区域 
	C_DOKAN_BATTLE_QUIT_AREA = RuleClick(roi_front=(10,36,50,14), roi_back=(10,36,50,14), name="dokan_battle_quit_area")


	# Image Rule Assets
	# 区域找绿标 
	I_GREEN_MARK = RuleImage(file="res/green_mark.png", roi_front=(157,220,979,229), roi_back=(157,220,979,229), threshold=0.6, method="Template matching", path="./tasks/Dokan/")
	# 区域找绿标 
	I_GREEN_MARK_1 = RuleImage(file="res/green_mark_1.png", roi_front=(157,220,979,229), roi_back=(157,220,979,229), threshold=0.6, method="Template matching", path="./tasks/Dokan/")
	# 道馆 
	I_DAOGUAN = RuleImage(file="res/Screenshots_daoguan.png", roi_front=(470,178,71,60), roi_back=(439,169,143,146), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 寮称号 
	I_GUILD_NAME_TITLE = RuleImage(file="res/Screenshots_guild_name_title.png", roi_front=(596,191,75,43), roi_back=(596,191,75,43), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 防守战报 
	I_FANGSHOU = RuleImage(file="res/Screenshots_fangshou.png", roi_front=(35,610,75,79), roi_back=(35,610,75,79), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 建立道馆  
	I_CREATE_DAOGUAN = RuleImage(file="res/Screenshots_create_daoguan.png", roi_front=(262,630,45,62), roi_back=(262,630,45,62), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 建立道馆 
	I_CREATE_DAOGUAN_SURE = RuleImage(file="res/Screenshots_create_daoguan_sure.png", roi_front=(766,409,100,55), roi_back=(766,409,100,55), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 已经建立道馆  
	I_CREATE_DAOGUAN_OK = RuleImage(file="res/Screenshots_create_daoguan_ok.png", roi_front=(262,630,45,62), roi_back=(262,630,45,62), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 建立道馆弹出页，红色关闭 
	I_RED_CLOSE = RuleImage(file="res/Screenshots_red_close.png", roi_front=(1175,108,41,42), roi_back=(1175,108,41,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 挑战 
	I_NEWTZ = RuleImage(file="res/Screenshots_newtz.png", roi_front=(798,482,44,39), roi_back=(0,0,1047,718), threshold=0.7, method="Template matching", path="./tasks/Dokan/")
	# 放弃突破 
	I_QUIT_DOKAN = RuleImage(file="res/Screenshots_quit_dokan.png", roi_front=(60,612,53,53), roi_back=(60,612,53,53), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 管理放弃道馆over 
	I_QUIT_DOKAN_OVER = RuleImage(file="res/Screenshots_quit_dokan_over.png", roi_front=(1056,211,55,28), roi_back=(1043,190,104,66), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 寮友同意放弃突破 
	I_CROWD_QUIT_DOKAN = RuleImage(file="res/Screenshots_crowd_quit_dokan.png", roi_front=(1059,244,77,71), roi_back=(1059,244,77,71), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 再战道馆 
	I_CONTINUE_DOKAN = RuleImage(file="res/Screenshots_continue_dokan.png", roi_front=(1177,246,71,67), roi_back=(1177,246,71,67), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 神社->道馆 
	I_RYOU_DOKAN = RuleImage(file="res/res_ryou_dokan.png", roi_front=(476,173,62,24), roi_back=(476,173,62,24), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# []选择竂 
	I_RYOU_DOKAN_RYOU_SELECT = RuleImage(file="res/res_ryou_dokan_ryou_select.png", roi_front=(567,15,144,42), roi_back=(567,15,144,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 可选的竂列表 
	I_RYOU_DOKAN_RYOU_LIST = RuleImage(file="res/res_ryou_dokan_ryou_list.png", roi_front=(567,15,144,42), roi_back=(567,15,144,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 是否已经成功进入道馆，上面中间的“道馆突破”文字 
	I_RYOU_DOKAN_CHECK = RuleImage(file="res/res_ryou_dokan_check.png", roi_front=(567,15,144,42), roi_back=(567,15,144,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击选项 
	I_RYOU_DOKAN_ATTACK_PRIORITY = RuleImage(file="res/res_ryou_dokan_priority.png", roi_front=(666,672,58,25), roi_back=(666,672,58,25), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击: 见习 
	I_RYOU_DOKAN_ATTACK_PRIORITY_0 = RuleImage(file="res/res_ryou_dokan_priority_0.png", roi_front=(98,170,94,43), roi_back=(98,170,94,43), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击: 初级 
	I_RYOU_DOKAN_ATTACK_PRIORITY_1 = RuleImage(file="res/res_ryou_dokan_priority_1.png", roi_front=(342,175,96,42), roi_back=(342,175,96,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击: 中级 
	I_RYOU_DOKAN_ATTACK_PRIORITY_2 = RuleImage(file="res/res_ryou_dokan_priority_2.png", roi_front=(585,175,89,35), roi_back=(585,175,89,35), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击: 高级 
	I_RYOU_DOKAN_ATTACK_PRIORITY_3 = RuleImage(file="res/res_ryou_dokan_priority_3.png", roi_front=(830,175,88,41), roi_back=(830,175,88,41), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 优先攻击: 黑脸 
	I_RYOU_DOKAN_ATTACK_PRIORITY_4 = RuleImage(file="res/res_ryou_dokan_priority_4.png", roi_front=(1072,178,94,39), roi_back=(1072,178,94,39), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：集结等待中。检查右下角的挑战是不是灰色的。FIXME 黄色和灰色的挑战截图总是傻傻分不清，先改用OCR 
	I_RYOU_DOKAN_GATHERING = RuleImage(file="res/res_ryou_dokan_gathering.png", roi_front=(653,76,46,26), roi_back=(653,76,46,26), threshold=0.85, method="Template matching", path="./tasks/Dokan/")
	# 状态：检查右下角有没有挑战？通常是失败了，并退出来到集结界面，可重新开始点击右下角挑战进入战斗 
	I_RYOU_DOKAN_START_CHALLENGE = RuleImage(file="res/res_ryou_dokan_start_challenge.png", roi_front=(1132,572,89,43), roi_back=(1132,572,89,43), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：达到失败次数，CD中。挑战次数恢复倒数 
	I_RYOU_DOKAN_CD1 = RuleImage(file="res/res_ryou_dokan_cd1.png", roi_front=(1068,500,146,27), roi_back=(1068,500,146,27), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：达到失败次数，CD中。观战按钮 
	I_RYOU_DOKAN_CD = RuleImage(file="res/res_ryou_dokan_cd.png", roi_front=(1122,566,117,74), roi_back=(1122,566,117,74), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：进入战斗，待开始，右下角图标。TODO 欠截图。 
	I_RYOU_DOKAN_IN_FIELD = RuleImage(file="res/res_ryou_dokan_in_field.png", roi_front=(1128,536,100,100), roi_back=(1032,492,239,210), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 馆主战等待中 
	I_DOKAN_BOSS_WAITING = RuleImage(file="res/res_dokan_boss_waiting.png", roi_front=(542,142,195,45), roi_back=(542,142,195,45), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 打馆主胜利 
	I_RYOU_DOKAN_WIN = RuleImage(file="res/res_ryou_dokan_win.png", roi_front=(628,60,45,33), roi_back=(628,60,45,33), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 打馆主失败 
	I_RYOU_DOKAN_FAIL = RuleImage(file="res/res_ryou_dokan_fail.png", roi_front=(454,44,56,46), roi_back=(454,44,56,46), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：进入战斗，待开始，右下角图标。 
	I_RYOU_DOKAN_IN_FIELD2 = RuleImage(file="res/res_ryou_dokan_in_field2.png", roi_front=(1131,562,88,48), roi_back=(1131,562,88,48), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：战斗中，左上角的加油图标 
	I_RYOU_DOKAN_FIGHTING = RuleImage(file="res/res_ryou_dokan_fighting.png", roi_front=(232,36,42,19), roi_back=(232,36,42,19), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：道馆已经结束 
	I_RYOU_DOKAN_FINISHED = RuleImage(file="res/res_ryou_dokan_finished.png", roi_front=(658,649,91,27), roi_back=(658,649,91,27), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 状态：道馆挑战失败，投票NO 
	I_RYOU_DOKAN_FAILED_VOTE_NO = RuleImage(file="res/res_ryou_dokan_failed_vote_no.png", roi_front=(567,15,144,42), roi_back=(567,15,144,42), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 进入加油相关：道馆战报按钮 
	I_RYOU_DOKAN_CHEERING_SCORES = RuleImage(file="res/res_ryou_dokan_cheering_scores.png", roi_front=(157,100,35,39), roi_back=(157,100,35,39), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 进入加油相关：前往战斗中的竂友 
	I_RYOU_DOKAN_CHEERING_ATTACKING_SAMA = RuleImage(file="res/res_ryou_dokan_cheering_attacking_sama.png", roi_front=(948,182,56,295), roi_back=(948,182,56,295), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 场景检测：阴阳竂 
	I_SCENE_RYOU = RuleImage(file="res/scene_ryou.png", roi_front=(1161,674,75,31), roi_back=(1161,674,75,31), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 查找道馆时,中间防守人数字样,为了定位该图下方的 防守人数数字 
	I_CENTER_POINT_PEOPLE_NUMBER = RuleImage(file="res/res_ryou_dokan_center_point_people_number.png", roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 查找道馆时,右侧道馆赏金图标,为了定位该图右侧的 赏金金额 
	I_RIGHTPAD_POINT_BOUNTY = RuleImage(file="res/res_ryou_dokan_rightpad_point_bounty.png", roi_front=(1050,0,230,0), roi_back=(1050,0,230,50), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 查找道馆时,中间信息卡片 馆主等级-修习 
	I_CENTER_GUANZHU_XIUXI = RuleImage(file="res/res_ryou_dokan_center_guanzhu_xiuxi.png", roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 寮境中上部的标志 
	I_RYOU_DOKAN_CENTER_TOP = RuleImage(file="res/res_ryou_dokan_center_top.png", roi_front=(500,20,300,70), roi_back=(500,20,300,70), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 左上角退出按钮- 
	I_RYOU_DOKAN_DOKAN_QUIT = RuleImage(file="res/res_ryou_dokan_dokan_quit.png", roi_front=(0,2,80,80), roi_back=(0,2,80,80), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 道馆攻破后夺得资金界面 
	I_RYOU_DOKAN_SPOILS_OF_DOKAN = RuleImage(file="res/res_ryou_dokan_spoils_of_dokan.png", roi_front=(480,400,400,100), roi_back=(480,400,400,100), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 今日可挑战次数:2次 
	I_RYOU_DOKAN_REMAIN_ATTACK_COUNT_TWO = RuleImage(file="res/res_ryou_dokan_remain_attack_count_two.png", roi_front=(650,610,110,80), roi_back=(650,610,110,80), threshold=0.9, method="Template matching", path="./tasks/Dokan/")
	# 查找道馆时,挑战按钮 
	I_CENTER_CHALLENGE = RuleImage(file="res/res_ryou_dokan_center_challenge.png", roi_front=(0,0,1280,720), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 正在查找道馆,还未选择 
	I_RYOU_DOKAN_FINDING_DOKAN = RuleImage(file="res/res_ryou_dokan_finding_dokan.png", roi_front=(980,60,100,160), roi_back=(980,60,100,160), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 已选择道馆 
	I_RYOU_DOKAN_FOUND_DOKAN = RuleImage(file="res/res_ryou_dokan_found_dokan.png", roi_front=(440,580,360,140), roi_back=(440,580,360,140), threshold=0.8, method="Template matching", path="./tasks/Dokan/")
	# 道馆进入式神录 
	I_PAGE_DOKAN_GOTO_SHIKIGAMI_RECORDS = RuleImage(file="res/page_dokan_goto_shikigami_records.png", roi_front=(1005,607,52,59), roi_back=(1005,607,52,59), threshold=0.8, method="Template matching", path="./tasks/Dokan/")


	# List Rule Assets
	# 这个是当前活跃的竂活动列表界面 
	L_RYOU_ACTIVITY_LIST = RuleList(folder="./tasks/Dokan/res", direction="vertical", mode="ocr", roi_back=(35,157,37,250), size=(42, 27), 
					 array=["道馆", "首领", "狭间"])


	# Ocr Rule Assets
	# 道馆开启状态 
	O_DOKAN_STATUS = RuleOcr(roi=(492,628,222,44), area=(492,628,222,44), mode="Full", method="Default", keyword="", name="dokan_status")
	# 选择寮1 
	O_DOKAN_READY_SEL1 = RuleOcr(roi=(1156,105,80,28), area=(1156,105,80,28), mode="Digit", method="Default", keyword="", name="dokan_ready_sel1")
	# 选择寮2 
	O_DOKAN_READY_SEL2 = RuleOcr(roi=(1156,255,80,28), area=(1156,255,80,28), mode="Digit", method="Default", keyword="", name="dokan_ready_sel2")
	# 选择寮3 
	O_DOKAN_READY_SEL3 = RuleOcr(roi=(1156,400,80,28), area=(1156,400,80,28), mode="Digit", method="Default", keyword="", name="dokan_ready_sel3")
	# 选择寮4 
	O_DOKAN_READY_SEL4 = RuleOcr(roi=(1156,545,80,28), area=(1156,545,80,28), mode="Digit", method="Default", keyword="", name="dokan_ready_sel4")
	# 道馆地图里找文字：万 
	O_DOKAN_MAP = RuleOcr(roi=(270,130,740,460), area=(270,130,740,460), mode="Full", method="Default", keyword="万", name="dokan_map")
	# 道馆里找文字：后开战 
	O_DOKAN_GATHERING = RuleOcr(roi=(535,75,211,29), area=(535,75,211,29), mode="Single", method="Default", keyword="开战", name="dokan_gathering")
	# 道馆里找文字：剩余突破时间 
	O_DOKAN_ATTACKING = RuleOcr(roi=(1122,546,92,51), area=(1122,546,92,51), mode="Single", method="Default", keyword="剩余", name="dokan_attacking")
	# 道馆里找文字：后挑战馆主 
	O_DOKAN_BOSS_WAITING = RuleOcr(roi=(603,148,130,32), area=(603,148,130,32), mode="Single", method="Default", keyword="馆主", name="dokan_boss_waiting")
	# 道馆里找文字：后关闭 
	O_DOKAN_SUCCEEDED = RuleOcr(roi=(655,76,49,28), area=(655,76,49,28), mode="Full", method="Default", keyword="关闭", name="dokan_succeeded")
	# 查找道馆时,右侧边栏中的赏金 
	O_DOKAN_RIGHTPAD_BOUNTY = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Single", method="Default", keyword="", name="dokan_rightpad_bounty")
	# 查找道馆时,右侧边栏中的寮名称 
	O_DOKAN_RIGHTPAD_NAME = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Single", method="Default", keyword="", name="dokan_rightpad_name")
	# 查找道馆时,中间卡片上防守人数 
	O_DOKAN_CENTER_PEOPLE_NUMBER = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Full", method="Default", keyword="", name="dokan_center_people_number")


	# Swipe Rule Assets
	# 道馆选择界面 右侧侧边栏 手指向上滑动 
	S_DOKAN_LIST_UP = RuleSwipe(roi_front=(1100,520,30,10), roi_back=(1100,90,30,10), mode="default", name="dokan_list_up")


