from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GoryouRealmAssets: 


	# Click Rule Assets
	# description 
	C_GR_C_1 = RuleClick(roi_front=(151,125,147,205), roi_back=(151,125,147,205), name="gr_c_1")
	# description 
	C_GR_C_2 = RuleClick(roi_front=(455,139,144,152), roi_back=(455,139,144,152), name="gr_c_2")
	# description 
	C_GR_C_3 = RuleClick(roi_front=(757,131,138,188), roi_back=(757,131,138,188), name="gr_c_3")
	# description 
	C_GR_C_4 = RuleClick(roi_front=(1064,149,128,124), roi_back=(1064,149,128,124), name="gr_c_4")


	# Image Rule Assets
	# 点击挑战 
	I_GR_FIRE = RuleImage(file="gr/gr_gr_fire.png", roi_front=(1097,582,100,100), roi_back=(1097,582,100,100), threshold=0.8, method="Template matching", path="./tasks/GoryouRealm/")
	# description 
	I_GR_LOCK = RuleImage(file="gr/gr_gr_lock.png", roi_front=(559,564,27,32), roi_back=(559,564,27,32), threshold=0.8, method="Template matching", path="./tasks/GoryouRealm/")
	# description 
	I_GR_UNLOCK = RuleImage(file="gr/gr_gr_unlock.png", roi_front=(556,562,26,33), roi_back=(556,562,26,33), threshold=0.8, method="Template matching", path="./tasks/GoryouRealm/")


	# Ocr Rule Assets
	# 多少张票 
	O_GR_TICKET = RuleOcr(roi=(920,21,100,41), area=(920,21,100,41), mode="Digit", method="Default", keyword="", name="gr_ticket")


