from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DailyTriflesAssets: 


	# Image Rule Assets
	# 进入普通召唤 
	I_BM_ENTER = RuleImage(file="broken_amulet/broken_amulet_bm_enter.png", roi_front=(435,601,62,68), roi_back=(435,601,62,68), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 召唤底部的确定 
	I_BM_CONFIRM = RuleImage(file="broken_amulet/broken_amulet_bm_confirm.png", roi_front=(418,620,173,59), roi_back=(418,620,173,59), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 再次召唤 
	I_BM_AGAIN = RuleImage(file="broken_amulet/broken_amulet_bm_again.png", roi_front=(686,617,178,60), roi_back=(686,617,178,60), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Ocr Rule Assets
	# 左上角的数量 
	O_BA_AMOUNT_1 = RuleOcr(roi=(568,15,79,29), area=(568,15,79,29), mode="Digit", method="Default", keyword="", name="ba_amount_1")
	# 召唤的时候的数量 
	O_BA_AMOUNT_2 = RuleOcr(roi=(762,570,118,35), area=(762,570,118,35), mode="DigitCounter", method="Default", keyword="", name="ba_amount_2")


	# Image Rule Assets
	# guild_info 
	I_GUILD_INFO = RuleImage(file="guild/guild_info.png", roi_front=(1181,625,50,45), roi_back=(1181,625,50,45), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# guild_management 
	I_GUILD_MANAGEMENT = RuleImage(file="guild/guild_management.png", roi_front=(260,84,66,45), roi_back=(260,84,66,45), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# guild_management_1 
	I_GUILD_MANAGEMENT_1 = RuleImage(file="guild/guild_management_1.png", roi_front=(352,612,75,37), roi_back=(352,612,75,37), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# recruit_members 
	I_RECRUIT_MEMBERS = RuleImage(file="guild/recruit_members.png", roi_front=(339,372,120,30), roi_back=(291,346,213,233), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# member_add 
	I_MEMBER_ADD = RuleImage(file="guild/member_add.png", roi_front=(1100,155,39,38), roi_back=(1075,137,86,400), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# member_flush 
	I_MEMBER_FLUSH = RuleImage(file="guild/member_flush.png", roi_front=(1004,615,92,32), roi_back=(1004,615,92,32), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 发布招新公告 
	I_POSTS = RuleImage(file="guild/posts.png", roi_front=(244,526,71,37), roi_back=(244,526,71,37), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Image Rule Assets
	# lottery_box 
	I_LOTTERY_BOX = RuleImage(file="lottery_box/lottery_box.png", roi_front=(489,317,20,17), roi_back=(6,137,1215,363), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# lottery_box_page 
	I_LOTTERY_BOX_PAGE = RuleImage(file="lottery_box/lottery_box_page.png", roi_front=(101,17,156,48), roi_back=(101,17,156,48), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# lottery_click 
	I_LOTTERY_CLICK = RuleImage(file="lottery_box/lottery_click.png", roi_front=(785,520,60,81), roi_back=(785,520,60,81), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Ocr Rule Assets
	# 抽奖次数 
	O_LOTTERY_NUMBER = RuleOcr(roi=(424,460,49,27), area=(424,460,49,27), mode="DigitCounter", method="Default", keyword="", name="lottery_number")


	# Swipe Rule Assets
	# description 
	S_SWIPE_LOTTERY_BOX = RuleSwipe(roi_front=(625,180,30,232), roi_back=(625,400,30,232), mode="default", name="swipe_lottery_box")


	# Image Rule Assets
	# description 
	I_L_FRIENDS = RuleImage(file="love/love_l_friends.png", roi_front=(67,625,70,72), roi_back=(67,625,70,72), threshold=0.9, method="Template matching", path="./tasks/DailyTrifles/")
	# l_friends_select 
	I_L_FRIENDS_SELECT = RuleImage(file="love/l_friends_select.png", roi_front=(165,100,52,30), roi_back=(141,86,103,56), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# description 
	I_L_LOVE = RuleImage(file="love/love_l_love.png", roi_front=(123,625,67,72), roi_back=(123,625,67,72), threshold=0.9, method="Template matching", path="./tasks/DailyTrifles/")
	# 一键收取 
	I_L_COLLECT = RuleImage(file="love/love_l_collect.png", roi_front=(47,537,129,56), roi_back=(47,537,129,56), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 吉闻 
	I_LUCK_MSG = RuleImage(file="love/Screenshots_luck_msg.png", roi_front=(22,47,46,27), roi_back=(22,47,46,27), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 一键祝福 
	I_ONE_CLICK_BLESS = RuleImage(file="love/Screenshots_one_click_bless.png", roi_front=(1115,500,93,33), roi_back=(1115,500,93,33), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 点击祝福 
	I_CLICK_BLESS = RuleImage(file="love/Screenshots_click_bless.png", roi_front=(617,442,92,39), roi_back=(617,442,92,39), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 吉闻页 
	I_LUCK_TITLE = RuleImage(file="love/Screenshots_luck_title.png", roi_front=(600,52,131,67), roi_back=(600,52,131,67), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 好友羁绊提升弹窗 
	I_FRIENDSHIP_UP = RuleImage(file="love/friendship_up.png", roi_front=(1147,80,27,28), roi_back=(1147,80,27,28), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Image Rule Assets
	# 集结 
	I_MASSED = RuleImage(file="massed/massed.png", roi_front=(213,521,50,56), roi_back=(213,521,50,56), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# battle 
	I_BATTLE = RuleImage(file="massed/battle.png", roi_front=(1068,605,117,35), roi_back=(1068,605,117,35), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# after_on 
	I_AFTER_ON = RuleImage(file="massed/after_on.png", roi_front=(1008,432,99,30), roi_back=(1008,432,99,30), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# click_any_position 
	I_CLICK_ANY_POSITION = RuleImage(file="massed/click_any_position.png", roi_front=(542,511,214,28), roi_back=(542,511,214,28), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Image Rule Assets
	# 式神碎片页面 
	I_PAGE_SHIKIGAMI_DEBRIS = RuleImage(file="shikigami_debris/page_shikigami_debris.png", roi_front=(370,82,104,29), roi_back=(370,82,104,29), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# goto_式神碎片页面 
	I_GOTO_SHIKIGAMI_DEBRIS = RuleImage(file="shikigami_debris/goto_shikigami_debris.png", roi_front=(36,650,63,42), roi_back=(36,650,63,42), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Image Rule Assets
	# 礼包屋 
	I_ROOM_GIFT = RuleImage(file="store/store_room_gift.png", roi_front=(1138,658,52,40), roi_back=(1119,621,103,94), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 日常（每日免费黑蛋） 
	I_GIFT_RECOMMEND = RuleImage(file="store/store_gift_recommend.png", roi_front=(1183,454,53,64), roi_back=(1161,74,105,484), threshold=0.7, method="Template matching", path="./tasks/DailyTrifles/")
	# 免费一抽领黑蛋 
	I_GIFT_SIGN = RuleImage(file="store/store_gift_sign.png", roi_front=(629,192,129,149), roi_back=(130,129,891,473), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 体力 
	I_SPECIAL_SUSHI = RuleImage(file="store/store_sushi.png", roi_front=(180,130,800,460), roi_back=(180,130,800,460), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 购买时货币类型为勾玉 
	I_STORE_COST_TYPE_JADE = RuleImage(file="store/store_cost_type_jade.png", roi_front=(555,540,171,54), roi_back=(555,540,171,54), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Ocr Rule Assets
	# 商店Special购买体力所需勾玉数量，roiBack为动态调整，故此设置为0，0，0，0 
	O_STORE_SUSHI_PRICE = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Digit", method="Default", keyword="", name="store_sushi_price")
	# 商店每日免费签到 
	O_STORE_FREE_SIGN = RuleOcr(roi=(136,173,414,204), area=(136,173,414,204), mode="Full", method="Default", keyword="免费", name="store_free_sign")
	# 商店签到页面（日常） 
	O_STORE_DAILY = RuleOcr(roi=(1183,73,51,484), area=(1183,73,51,484), mode="Full", method="Default", keyword="日常", name="store_daily")


	# Image Rule Assets
	# 点击今忆召唤票 
	I_RECALL_TICKET = RuleImage(file="summonRecall/recall_ticket.png", roi_front=(595,586,65,76), roi_back=(595,586,65,76), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 今忆召唤单抽 
	I_RECALL_ONE_TICKET = RuleImage(file="summonRecall/recall_one_ticket.png", roi_front=(459,604,76,76), roi_back=(459,604,76,76), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# description 
	I_RECALL_SM_CONFIRM = RuleImage(file="summonRecall/recall_sm_confirm.png", roi_front=(424,628,174,61), roi_back=(424,628,174,61), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 抽到的时候出现的 
	I_SM_CONFIRM_2 = RuleImage(file="summonRecall/sm_sm_confirm_2.png", roi_front=(377,630,206,62), roi_back=(377,630,206,62), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


	# Ocr Rule Assets
	# 今忆抽卡区域 
	O_RECALL_TICKET_AREA = RuleOcr(roi=(590,660,100,32), area=(590,660,100,32), mode="Single", method="Default", keyword="", name="recall_ticket_area")
	# 选择抽卡区域 
	O_SELECT_SM = RuleOcr(roi=(0,0,100,720), area=(0,0,100,720), mode="Single", method="Default", keyword="", name="select_sm")
	# description 
	O_SELECT_SM1 = RuleOcr(roi=(27,130,45,38), area=(27,130,45,38), mode="Single", method="Default", keyword="", name="select_sm1")
	# description 
	O_SELECT_SM2 = RuleOcr(roi=(26,216,45,38), area=(26,216,45,38), mode="Single", method="Default", keyword="", name="select_sm2")
	# description 
	O_SELECT_SM3 = RuleOcr(roi=(26,304,45,38), area=(26,304,45,38), mode="Single", method="Default", keyword="", name="select_sm3")
	# description 
	O_SELECT_SM4 = RuleOcr(roi=(26,397,45,38), area=(26,397,45,38), mode="Single", method="Default", keyword="", name="select_sm4")


	# Image Rule Assets
	# 召唤商店 
	I_SUMMON_STORE = RuleImage(file="summon_store/summon_store.png", roi_front=(1214,626,40,37), roi_back=(1214,626,40,37), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 召唤商店page 
	I_SUMMON_STORE_PAGE = RuleImage(file="summon_store/summon_store_page.png", roi_front=(99,11,185,59), roi_back=(99,11,185,59), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 祈愿福礼 
	I_SUMMON_STORE_LUCKY = RuleImage(file="summon_store/summon_store_lucky.png", roi_front=(94,102,84,33), roi_back=(94,102,84,33), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 免费 
	I_SUMMON_STORE_FREE = RuleImage(file="summon_store/summon_store_free.png", roi_front=(394,581,106,37), roi_back=(394,581,106,37), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 免费_1 
	I_SUMMON_STORE_FREE_1 = RuleImage(file="summon_store/summon_store_free_1.png", roi_front=(561,510,167,53), roi_back=(561,510,167,53), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# 已领取 
	I_SUMMON_STORE_FREE_OVER = RuleImage(file="summon_store/summon_store_free_over.png", roi_front=(394,581,106,37), roi_back=(394,581,106,37), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_1 
	I_FREE_1 = RuleImage(file="summon_store/free_1.png", roi_front=(360,493,31,30), roi_back=(360,493,31,30), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_2 
	I_FREE_2 = RuleImage(file="summon_store/free_2.png", roi_front=(430,494,38,24), roi_back=(430,494,38,24), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_3 
	I_FREE_3 = RuleImage(file="summon_store/free_3.png", roi_front=(502,490,41,35), roi_back=(502,490,41,35), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_3_over 
	I_FREE_3_OVER = RuleImage(file="summon_store/free_3_over.png", roi_front=(502,490,41,35), roi_back=(502,490,41,35), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_2_over 
	I_FREE_2_OVER = RuleImage(file="summon_store/free_2_over.png", roi_front=(430,494,38,24), roi_back=(430,494,38,24), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")
	# free_1_over 
	I_FREE_1_OVER = RuleImage(file="summon_store/free_1_over.png", roi_front=(360,493,31,30), roi_back=(360,493,31,30), threshold=0.8, method="Template matching", path="./tasks/DailyTrifles/")


