from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class EvoZoneAssets: 


	# Image Rule Assets
	# description 
	I_EVOZONE_LOCK = RuleImage(file="o/o_evozone_lock.png", roi_front=(558,565,31,32), roi_back=(548,554,53,54), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# description 
	I_EVOZONE_UNLOCK = RuleImage(file="o/o_evozone_unlock.png", roi_front=(560,565,26,29), roi_back=(551,557,43,45), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# 式神录 
	I_SHI_RECORDS = RuleImage(file="o/o_shi_records.png", roi_front=(821,638,48,45), roi_back=(821,638,48,45), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# 火麒麟进入 
	I_FIRE_KIRIN = RuleImage(file="o/o_fire_kirin.png", roi_front=(84,126,217,406), roi_back=(84,126,217,406), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# 风麒麟进入 
	I_WIND_KIRIN = RuleImage(file="o/o_wind_kirin.png", roi_front=(377,126,232,420), roi_back=(377,126,232,420), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# 水麒麟进入 
	I_WATER_KIRIN = RuleImage(file="o/o_water_kirin.png", roi_front=(671,122,236,420), roi_back=(671,122,236,420), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")
	# 雷麒麟进入 
	I_LIGHTNING_KIRIN = RuleImage(file="o/o_lightning_kirin.png", roi_front=(967,121,239,419), roi_back=(967,121,239,419), threshold=0.8, method="Template matching", path="./tasks/EvoZone/")


	# List Rule Assets
	# 这个是觉醒界面选择不同层数的 
	L_LAYER_LIST = RuleList(folder="./tasks/EvoZone/res", direction="vertical", mode="ocr", roi_back=(125,88,80,602), size=(44, 88), 
					 array=["壹层", "贰层", "叁层", "肆层", "伍层", "陆层", "柒层", "捌层", "玖层", "拾层"])


	# Ocr Rule Assets
	# Ocr-description 
	O_O_TEST_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_test_ocr")


